// Code generated by ent, DO NOT EDIT.

package projectconcept

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/predicate"
)

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.ProjectConcept {
	return predicate.ProjectConcept(sql.FieldEQ(FieldProjectID, v))
}

// ConceptID applies equality check predicate on the "concept_id" field. It's identical to ConceptIDEQ.
func ConceptID(v uuid.UUID) predicate.ProjectConcept {
	return predicate.ProjectConcept(sql.FieldEQ(FieldConceptID, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.ProjectConcept {
	return predicate.ProjectConcept(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.ProjectConcept {
	return predicate.ProjectConcept(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.ProjectConcept {
	return predicate.ProjectConcept(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.ProjectConcept {
	return predicate.ProjectConcept(sql.FieldNotIn(FieldProjectID, vs...))
}

// ConceptIDEQ applies the EQ predicate on the "concept_id" field.
func ConceptIDEQ(v uuid.UUID) predicate.ProjectConcept {
	return predicate.ProjectConcept(sql.FieldEQ(FieldConceptID, v))
}

// ConceptIDNEQ applies the NEQ predicate on the "concept_id" field.
func ConceptIDNEQ(v uuid.UUID) predicate.ProjectConcept {
	return predicate.ProjectConcept(sql.FieldNEQ(FieldConceptID, v))
}

// ConceptIDIn applies the In predicate on the "concept_id" field.
func ConceptIDIn(vs ...uuid.UUID) predicate.ProjectConcept {
	return predicate.ProjectConcept(sql.FieldIn(FieldConceptID, vs...))
}

// ConceptIDNotIn applies the NotIn predicate on the "concept_id" field.
func ConceptIDNotIn(vs ...uuid.UUID) predicate.ProjectConcept {
	return predicate.ProjectConcept(sql.FieldNotIn(FieldConceptID, vs...))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.ProjectConcept {
	return predicate.ProjectConcept(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, ProjectColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.ProjectConcept {
	return predicate.ProjectConcept(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasConcept applies the HasEdge predicate on the "concept" edge.
func HasConcept() predicate.ProjectConcept {
	return predicate.ProjectConcept(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, ConceptColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, ConceptTable, ConceptColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConceptWith applies the HasEdge predicate on the "concept" edge with a given conditions (other predicates).
func HasConceptWith(preds ...predicate.Concept) predicate.ProjectConcept {
	return predicate.ProjectConcept(func(s *sql.Selector) {
		step := newConceptStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProjectConcept) predicate.ProjectConcept {
	return predicate.ProjectConcept(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProjectConcept) predicate.ProjectConcept {
	return predicate.ProjectConcept(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProjectConcept) predicate.ProjectConcept {
	return predicate.ProjectConcept(sql.NotPredicates(p))
}
