// Code generated by ent, DO NOT EDIT.

package tutorialconcept

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/predicate"
)

// ContentID applies equality check predicate on the "content_id" field. It's identical to ContentIDEQ.
func ContentID(v uuid.UUID) predicate.TutorialConcept {
	return predicate.TutorialConcept(sql.FieldEQ(FieldContentID, v))
}

// ConceptID applies equality check predicate on the "concept_id" field. It's identical to ConceptIDEQ.
func ConceptID(v uuid.UUID) predicate.TutorialConcept {
	return predicate.TutorialConcept(sql.FieldEQ(FieldConceptID, v))
}

// ContentIDEQ applies the EQ predicate on the "content_id" field.
func ContentIDEQ(v uuid.UUID) predicate.TutorialConcept {
	return predicate.TutorialConcept(sql.FieldEQ(FieldContentID, v))
}

// ContentIDNEQ applies the NEQ predicate on the "content_id" field.
func ContentIDNEQ(v uuid.UUID) predicate.TutorialConcept {
	return predicate.TutorialConcept(sql.FieldNEQ(FieldContentID, v))
}

// ContentIDIn applies the In predicate on the "content_id" field.
func ContentIDIn(vs ...uuid.UUID) predicate.TutorialConcept {
	return predicate.TutorialConcept(sql.FieldIn(FieldContentID, vs...))
}

// ContentIDNotIn applies the NotIn predicate on the "content_id" field.
func ContentIDNotIn(vs ...uuid.UUID) predicate.TutorialConcept {
	return predicate.TutorialConcept(sql.FieldNotIn(FieldContentID, vs...))
}

// ConceptIDEQ applies the EQ predicate on the "concept_id" field.
func ConceptIDEQ(v uuid.UUID) predicate.TutorialConcept {
	return predicate.TutorialConcept(sql.FieldEQ(FieldConceptID, v))
}

// ConceptIDNEQ applies the NEQ predicate on the "concept_id" field.
func ConceptIDNEQ(v uuid.UUID) predicate.TutorialConcept {
	return predicate.TutorialConcept(sql.FieldNEQ(FieldConceptID, v))
}

// ConceptIDIn applies the In predicate on the "concept_id" field.
func ConceptIDIn(vs ...uuid.UUID) predicate.TutorialConcept {
	return predicate.TutorialConcept(sql.FieldIn(FieldConceptID, vs...))
}

// ConceptIDNotIn applies the NotIn predicate on the "concept_id" field.
func ConceptIDNotIn(vs ...uuid.UUID) predicate.TutorialConcept {
	return predicate.TutorialConcept(sql.FieldNotIn(FieldConceptID, vs...))
}

// HasContent applies the HasEdge predicate on the "content" edge.
func HasContent() predicate.TutorialConcept {
	return predicate.TutorialConcept(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, ContentColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, ContentTable, ContentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContentWith applies the HasEdge predicate on the "content" edge with a given conditions (other predicates).
func HasContentWith(preds ...predicate.TutorialContent) predicate.TutorialConcept {
	return predicate.TutorialConcept(func(s *sql.Selector) {
		step := newContentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasConcept applies the HasEdge predicate on the "concept" edge.
func HasConcept() predicate.TutorialConcept {
	return predicate.TutorialConcept(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, ConceptColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, ConceptTable, ConceptColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConceptWith applies the HasEdge predicate on the "concept" edge with a given conditions (other predicates).
func HasConceptWith(preds ...predicate.Concept) predicate.TutorialConcept {
	return predicate.TutorialConcept(func(s *sql.Selector) {
		step := newConceptStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TutorialConcept) predicate.TutorialConcept {
	return predicate.TutorialConcept(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TutorialConcept) predicate.TutorialConcept {
	return predicate.TutorialConcept(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TutorialConcept) predicate.TutorialConcept {
	return predicate.TutorialConcept(sql.NotPredicates(p))
}
