// Code generated by ent, DO NOT EDIT.

package project

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldID, id))
}

// GhRepoID applies equality check predicate on the "gh_repo_id" field. It's identical to GhRepoIDEQ.
func GhRepoID(v int64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldGhRepoID, v))
}

// OwnerHandle applies equality check predicate on the "owner_handle" field. It's identical to OwnerHandleEQ.
func OwnerHandle(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldOwnerHandle, v))
}

// RepoName applies equality check predicate on the "repo_name" field. It's identical to RepoNameEQ.
func RepoName(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldRepoName, v))
}

// FullName applies equality check predicate on the "full_name" field. It's identical to FullNameEQ.
func FullName(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldFullName, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldLanguage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCreatedAt, v))
}

// GhRepoIDEQ applies the EQ predicate on the "gh_repo_id" field.
func GhRepoIDEQ(v int64) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldGhRepoID, v))
}

// GhRepoIDNEQ applies the NEQ predicate on the "gh_repo_id" field.
func GhRepoIDNEQ(v int64) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldGhRepoID, v))
}

// GhRepoIDIn applies the In predicate on the "gh_repo_id" field.
func GhRepoIDIn(vs ...int64) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldGhRepoID, vs...))
}

// GhRepoIDNotIn applies the NotIn predicate on the "gh_repo_id" field.
func GhRepoIDNotIn(vs ...int64) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldGhRepoID, vs...))
}

// GhRepoIDGT applies the GT predicate on the "gh_repo_id" field.
func GhRepoIDGT(v int64) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldGhRepoID, v))
}

// GhRepoIDGTE applies the GTE predicate on the "gh_repo_id" field.
func GhRepoIDGTE(v int64) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldGhRepoID, v))
}

// GhRepoIDLT applies the LT predicate on the "gh_repo_id" field.
func GhRepoIDLT(v int64) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldGhRepoID, v))
}

// GhRepoIDLTE applies the LTE predicate on the "gh_repo_id" field.
func GhRepoIDLTE(v int64) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldGhRepoID, v))
}

// OwnerHandleEQ applies the EQ predicate on the "owner_handle" field.
func OwnerHandleEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldOwnerHandle, v))
}

// OwnerHandleNEQ applies the NEQ predicate on the "owner_handle" field.
func OwnerHandleNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldOwnerHandle, v))
}

// OwnerHandleIn applies the In predicate on the "owner_handle" field.
func OwnerHandleIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldOwnerHandle, vs...))
}

// OwnerHandleNotIn applies the NotIn predicate on the "owner_handle" field.
func OwnerHandleNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldOwnerHandle, vs...))
}

// OwnerHandleGT applies the GT predicate on the "owner_handle" field.
func OwnerHandleGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldOwnerHandle, v))
}

// OwnerHandleGTE applies the GTE predicate on the "owner_handle" field.
func OwnerHandleGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldOwnerHandle, v))
}

// OwnerHandleLT applies the LT predicate on the "owner_handle" field.
func OwnerHandleLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldOwnerHandle, v))
}

// OwnerHandleLTE applies the LTE predicate on the "owner_handle" field.
func OwnerHandleLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldOwnerHandle, v))
}

// OwnerHandleContains applies the Contains predicate on the "owner_handle" field.
func OwnerHandleContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldOwnerHandle, v))
}

// OwnerHandleHasPrefix applies the HasPrefix predicate on the "owner_handle" field.
func OwnerHandleHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldOwnerHandle, v))
}

// OwnerHandleHasSuffix applies the HasSuffix predicate on the "owner_handle" field.
func OwnerHandleHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldOwnerHandle, v))
}

// OwnerHandleEqualFold applies the EqualFold predicate on the "owner_handle" field.
func OwnerHandleEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldOwnerHandle, v))
}

// OwnerHandleContainsFold applies the ContainsFold predicate on the "owner_handle" field.
func OwnerHandleContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldOwnerHandle, v))
}

// RepoNameEQ applies the EQ predicate on the "repo_name" field.
func RepoNameEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldRepoName, v))
}

// RepoNameNEQ applies the NEQ predicate on the "repo_name" field.
func RepoNameNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldRepoName, v))
}

// RepoNameIn applies the In predicate on the "repo_name" field.
func RepoNameIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldRepoName, vs...))
}

// RepoNameNotIn applies the NotIn predicate on the "repo_name" field.
func RepoNameNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldRepoName, vs...))
}

// RepoNameGT applies the GT predicate on the "repo_name" field.
func RepoNameGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldRepoName, v))
}

// RepoNameGTE applies the GTE predicate on the "repo_name" field.
func RepoNameGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldRepoName, v))
}

// RepoNameLT applies the LT predicate on the "repo_name" field.
func RepoNameLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldRepoName, v))
}

// RepoNameLTE applies the LTE predicate on the "repo_name" field.
func RepoNameLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldRepoName, v))
}

// RepoNameContains applies the Contains predicate on the "repo_name" field.
func RepoNameContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldRepoName, v))
}

// RepoNameHasPrefix applies the HasPrefix predicate on the "repo_name" field.
func RepoNameHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldRepoName, v))
}

// RepoNameHasSuffix applies the HasSuffix predicate on the "repo_name" field.
func RepoNameHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldRepoName, v))
}

// RepoNameEqualFold applies the EqualFold predicate on the "repo_name" field.
func RepoNameEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldRepoName, v))
}

// RepoNameContainsFold applies the ContainsFold predicate on the "repo_name" field.
func RepoNameContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldRepoName, v))
}

// FullNameEQ applies the EQ predicate on the "full_name" field.
func FullNameEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldFullName, v))
}

// FullNameNEQ applies the NEQ predicate on the "full_name" field.
func FullNameNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldFullName, v))
}

// FullNameIn applies the In predicate on the "full_name" field.
func FullNameIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldFullName, vs...))
}

// FullNameNotIn applies the NotIn predicate on the "full_name" field.
func FullNameNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldFullName, vs...))
}

// FullNameGT applies the GT predicate on the "full_name" field.
func FullNameGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldFullName, v))
}

// FullNameGTE applies the GTE predicate on the "full_name" field.
func FullNameGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldFullName, v))
}

// FullNameLT applies the LT predicate on the "full_name" field.
func FullNameLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldFullName, v))
}

// FullNameLTE applies the LTE predicate on the "full_name" field.
func FullNameLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldFullName, v))
}

// FullNameContains applies the Contains predicate on the "full_name" field.
func FullNameContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldFullName, v))
}

// FullNameHasPrefix applies the HasPrefix predicate on the "full_name" field.
func FullNameHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldFullName, v))
}

// FullNameHasSuffix applies the HasSuffix predicate on the "full_name" field.
func FullNameHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldFullName, v))
}

// FullNameEqualFold applies the EqualFold predicate on the "full_name" field.
func FullNameEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldFullName, v))
}

// FullNameContainsFold applies the ContainsFold predicate on the "full_name" field.
func FullNameContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldFullName, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.Project {
	return predicate.Project(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.Project {
	return predicate.Project(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageIsNil applies the IsNil predicate on the "language" field.
func LanguageIsNil() predicate.Project {
	return predicate.Project(sql.FieldIsNull(FieldLanguage))
}

// LanguageNotNil applies the NotNil predicate on the "language" field.
func LanguageNotNil() predicate.Project {
	return predicate.Project(sql.FieldNotNull(FieldLanguage))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.Project {
	return predicate.Project(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.Project {
	return predicate.Project(sql.FieldContainsFold(FieldLanguage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Project {
	return predicate.Project(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Project {
	return predicate.Project(sql.FieldLTE(FieldCreatedAt, v))
}

// HasIssues applies the HasEdge predicate on the "issues" edge.
func HasIssues() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, IssuesTable, IssuesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIssuesWith applies the HasEdge predicate on the "issues" edge with a given conditions (other predicates).
func HasIssuesWith(preds ...predicate.GithubIssue) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newIssuesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasConcepts applies the HasEdge predicate on the "concepts" edge.
func HasConcepts() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, ConceptsTable, ConceptsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConceptsWith applies the HasEdge predicate on the "concepts" edge with a given conditions (other predicates).
func HasConceptsWith(preds ...predicate.Concept) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newConceptsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProjectConcepts applies the HasEdge predicate on the "project_concepts" edge.
func HasProjectConcepts() predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ProjectConceptsTable, ProjectConceptsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectConceptsWith applies the HasEdge predicate on the "project_concepts" edge with a given conditions (other predicates).
func HasProjectConceptsWith(preds ...predicate.ProjectConcept) predicate.Project {
	return predicate.Project(func(s *sql.Selector) {
		step := newProjectConceptsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Project) predicate.Project {
	return predicate.Project(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Project) predicate.Project {
	return predicate.Project(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Project) predicate.Project {
	return predicate.Project(sql.NotPredicates(p))
}
