// Code generated by ent, DO NOT EDIT.

package githubissue

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the githubissue type in the database.
	Label = "github_issue"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldIssueNumber holds the string denoting the issue_number field in the database.
	FieldIssueNumber = "issue_number"
	// FieldGhIssueID holds the string denoting the gh_issue_id field in the database.
	FieldGhIssueID = "gh_issue_id"
	// FieldRawData holds the string denoting the raw_data field in the database.
	FieldRawData = "raw_data"
	// FieldLastSyncedAt holds the string denoting the last_synced_at field in the database.
	FieldLastSyncedAt = "last_synced_at"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeTutorialContent holds the string denoting the tutorial_content edge name in mutations.
	EdgeTutorialContent = "tutorial_content"
	// Table holds the table name of the githubissue in the database.
	Table = "github_issues"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "github_issues"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// TutorialContentTable is the table that holds the tutorial_content relation/edge.
	TutorialContentTable = "tutorial_contents"
	// TutorialContentInverseTable is the table name for the TutorialContent entity.
	// It exists in this package in order to avoid circular dependency with the "tutorialcontent" package.
	TutorialContentInverseTable = "tutorial_contents"
	// TutorialContentColumn is the table column denoting the tutorial_content relation/edge.
	TutorialContentColumn = "issue_id"
)

// Columns holds all SQL columns for githubissue fields.
var Columns = []string{
	FieldID,
	FieldProjectID,
	FieldIssueNumber,
	FieldGhIssueID,
	FieldRawData,
	FieldLastSyncedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IssueNumberValidator is a validator for the "issue_number" field. It is called by the builders before save.
	IssueNumberValidator func(int) error
	// DefaultLastSyncedAt holds the default value on creation for the "last_synced_at" field.
	DefaultLastSyncedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the GithubIssue queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByIssueNumber orders the results by the issue_number field.
func ByIssueNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssueNumber, opts...).ToFunc()
}

// ByGhIssueID orders the results by the gh_issue_id field.
func ByGhIssueID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGhIssueID, opts...).ToFunc()
}

// ByLastSyncedAt orders the results by the last_synced_at field.
func ByLastSyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncedAt, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByTutorialContentField orders the results by tutorial_content field.
func ByTutorialContentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTutorialContentStep(), sql.OrderByField(field, opts...))
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newTutorialContentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TutorialContentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, TutorialContentTable, TutorialContentColumn),
	)
}
