// Code generated by ent, DO NOT EDIT.

package githubissue

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldLTE(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldEQ(FieldProjectID, v))
}

// IssueNumber applies equality check predicate on the "issue_number" field. It's identical to IssueNumberEQ.
func IssueNumber(v int) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldEQ(FieldIssueNumber, v))
}

// GhIssueID applies equality check predicate on the "gh_issue_id" field. It's identical to GhIssueIDEQ.
func GhIssueID(v int64) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldEQ(FieldGhIssueID, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldEQ(FieldLastSyncedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldNotIn(FieldProjectID, vs...))
}

// IssueNumberEQ applies the EQ predicate on the "issue_number" field.
func IssueNumberEQ(v int) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldEQ(FieldIssueNumber, v))
}

// IssueNumberNEQ applies the NEQ predicate on the "issue_number" field.
func IssueNumberNEQ(v int) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldNEQ(FieldIssueNumber, v))
}

// IssueNumberIn applies the In predicate on the "issue_number" field.
func IssueNumberIn(vs ...int) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldIn(FieldIssueNumber, vs...))
}

// IssueNumberNotIn applies the NotIn predicate on the "issue_number" field.
func IssueNumberNotIn(vs ...int) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldNotIn(FieldIssueNumber, vs...))
}

// IssueNumberGT applies the GT predicate on the "issue_number" field.
func IssueNumberGT(v int) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldGT(FieldIssueNumber, v))
}

// IssueNumberGTE applies the GTE predicate on the "issue_number" field.
func IssueNumberGTE(v int) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldGTE(FieldIssueNumber, v))
}

// IssueNumberLT applies the LT predicate on the "issue_number" field.
func IssueNumberLT(v int) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldLT(FieldIssueNumber, v))
}

// IssueNumberLTE applies the LTE predicate on the "issue_number" field.
func IssueNumberLTE(v int) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldLTE(FieldIssueNumber, v))
}

// GhIssueIDEQ applies the EQ predicate on the "gh_issue_id" field.
func GhIssueIDEQ(v int64) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldEQ(FieldGhIssueID, v))
}

// GhIssueIDNEQ applies the NEQ predicate on the "gh_issue_id" field.
func GhIssueIDNEQ(v int64) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldNEQ(FieldGhIssueID, v))
}

// GhIssueIDIn applies the In predicate on the "gh_issue_id" field.
func GhIssueIDIn(vs ...int64) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldIn(FieldGhIssueID, vs...))
}

// GhIssueIDNotIn applies the NotIn predicate on the "gh_issue_id" field.
func GhIssueIDNotIn(vs ...int64) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldNotIn(FieldGhIssueID, vs...))
}

// GhIssueIDGT applies the GT predicate on the "gh_issue_id" field.
func GhIssueIDGT(v int64) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldGT(FieldGhIssueID, v))
}

// GhIssueIDGTE applies the GTE predicate on the "gh_issue_id" field.
func GhIssueIDGTE(v int64) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldGTE(FieldGhIssueID, v))
}

// GhIssueIDLT applies the LT predicate on the "gh_issue_id" field.
func GhIssueIDLT(v int64) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldLT(FieldGhIssueID, v))
}

// GhIssueIDLTE applies the LTE predicate on the "gh_issue_id" field.
func GhIssueIDLTE(v int64) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldLTE(FieldGhIssueID, v))
}

// RawDataIsNil applies the IsNil predicate on the "raw_data" field.
func RawDataIsNil() predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldIsNull(FieldRawData))
}

// RawDataNotNil applies the NotNil predicate on the "raw_data" field.
func RawDataNotNil() predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldNotNull(FieldRawData))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.GithubIssue {
	return predicate.GithubIssue(sql.FieldLTE(FieldLastSyncedAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.GithubIssue {
	return predicate.GithubIssue(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.GithubIssue {
	return predicate.GithubIssue(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTutorialContent applies the HasEdge predicate on the "tutorial_content" edge.
func HasTutorialContent() predicate.GithubIssue {
	return predicate.GithubIssue(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, TutorialContentTable, TutorialContentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTutorialContentWith applies the HasEdge predicate on the "tutorial_content" edge with a given conditions (other predicates).
func HasTutorialContentWith(preds ...predicate.TutorialContent) predicate.GithubIssue {
	return predicate.GithubIssue(func(s *sql.Selector) {
		step := newTutorialContentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GithubIssue) predicate.GithubIssue {
	return predicate.GithubIssue(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GithubIssue) predicate.GithubIssue {
	return predicate.GithubIssue(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GithubIssue) predicate.GithubIssue {
	return predicate.GithubIssue(sql.NotPredicates(p))
}
