// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/issuesight/issuesight/internal/platform/db/ent/concept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/conceptrelationship"
	"github.com/issuesight/issuesight/internal/platform/db/ent/githubissue"
	"github.com/issuesight/issuesight/internal/platform/db/ent/project"
	"github.com/issuesight/issuesight/internal/platform/db/ent/projectconcept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorial"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialconcept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialcontent"
	"github.com/issuesight/issuesight/internal/platform/db/ent/user"
	"github.com/issuesight/issuesight/internal/platform/db/ent/useridentity"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Concept is the client for interacting with the Concept builders.
	Concept *ConceptClient
	// ConceptRelationship is the client for interacting with the ConceptRelationship builders.
	ConceptRelationship *ConceptRelationshipClient
	// GithubIssue is the client for interacting with the GithubIssue builders.
	GithubIssue *GithubIssueClient
	// Project is the client for interacting with the Project builders.
	Project *ProjectClient
	// ProjectConcept is the client for interacting with the ProjectConcept builders.
	ProjectConcept *ProjectConceptClient
	// Tutorial is the client for interacting with the Tutorial builders.
	Tutorial *TutorialClient
	// TutorialConcept is the client for interacting with the TutorialConcept builders.
	TutorialConcept *TutorialConceptClient
	// TutorialContent is the client for interacting with the TutorialContent builders.
	TutorialContent *TutorialContentClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// UserIdentity is the client for interacting with the UserIdentity builders.
	UserIdentity *UserIdentityClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Concept = NewConceptClient(c.config)
	c.ConceptRelationship = NewConceptRelationshipClient(c.config)
	c.GithubIssue = NewGithubIssueClient(c.config)
	c.Project = NewProjectClient(c.config)
	c.ProjectConcept = NewProjectConceptClient(c.config)
	c.Tutorial = NewTutorialClient(c.config)
	c.TutorialConcept = NewTutorialConceptClient(c.config)
	c.TutorialContent = NewTutorialContentClient(c.config)
	c.User = NewUserClient(c.config)
	c.UserIdentity = NewUserIdentityClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		Concept:             NewConceptClient(cfg),
		ConceptRelationship: NewConceptRelationshipClient(cfg),
		GithubIssue:         NewGithubIssueClient(cfg),
		Project:             NewProjectClient(cfg),
		ProjectConcept:      NewProjectConceptClient(cfg),
		Tutorial:            NewTutorialClient(cfg),
		TutorialConcept:     NewTutorialConceptClient(cfg),
		TutorialContent:     NewTutorialContentClient(cfg),
		User:                NewUserClient(cfg),
		UserIdentity:        NewUserIdentityClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		Concept:             NewConceptClient(cfg),
		ConceptRelationship: NewConceptRelationshipClient(cfg),
		GithubIssue:         NewGithubIssueClient(cfg),
		Project:             NewProjectClient(cfg),
		ProjectConcept:      NewProjectConceptClient(cfg),
		Tutorial:            NewTutorialClient(cfg),
		TutorialConcept:     NewTutorialConceptClient(cfg),
		TutorialContent:     NewTutorialContentClient(cfg),
		User:                NewUserClient(cfg),
		UserIdentity:        NewUserIdentityClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Concept.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.Concept, c.ConceptRelationship, c.GithubIssue, c.Project, c.ProjectConcept,
		c.Tutorial, c.TutorialConcept, c.TutorialContent, c.User, c.UserIdentity,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.Concept, c.ConceptRelationship, c.GithubIssue, c.Project, c.ProjectConcept,
		c.Tutorial, c.TutorialConcept, c.TutorialContent, c.User, c.UserIdentity,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ConceptMutation:
		return c.Concept.mutate(ctx, m)
	case *ConceptRelationshipMutation:
		return c.ConceptRelationship.mutate(ctx, m)
	case *GithubIssueMutation:
		return c.GithubIssue.mutate(ctx, m)
	case *ProjectMutation:
		return c.Project.mutate(ctx, m)
	case *ProjectConceptMutation:
		return c.ProjectConcept.mutate(ctx, m)
	case *TutorialMutation:
		return c.Tutorial.mutate(ctx, m)
	case *TutorialConceptMutation:
		return c.TutorialConcept.mutate(ctx, m)
	case *TutorialContentMutation:
		return c.TutorialContent.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *UserIdentityMutation:
		return c.UserIdentity.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ConceptClient is a client for the Concept schema.
type ConceptClient struct {
	config
}

// NewConceptClient returns a client for the Concept from the given config.
func NewConceptClient(c config) *ConceptClient {
	return &ConceptClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `concept.Hooks(f(g(h())))`.
func (c *ConceptClient) Use(hooks ...Hook) {
	c.hooks.Concept = append(c.hooks.Concept, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `concept.Intercept(f(g(h())))`.
func (c *ConceptClient) Intercept(interceptors ...Interceptor) {
	c.inters.Concept = append(c.inters.Concept, interceptors...)
}

// Create returns a builder for creating a Concept entity.
func (c *ConceptClient) Create() *ConceptCreate {
	mutation := newConceptMutation(c.config, OpCreate)
	return &ConceptCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Concept entities.
func (c *ConceptClient) CreateBulk(builders ...*ConceptCreate) *ConceptCreateBulk {
	return &ConceptCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ConceptClient) MapCreateBulk(slice any, setFunc func(*ConceptCreate, int)) *ConceptCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ConceptCreateBulk{err: fmt.Errorf("calling to ConceptClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ConceptCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ConceptCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Concept.
func (c *ConceptClient) Update() *ConceptUpdate {
	mutation := newConceptMutation(c.config, OpUpdate)
	return &ConceptUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ConceptClient) UpdateOne(_m *Concept) *ConceptUpdateOne {
	mutation := newConceptMutation(c.config, OpUpdateOne, withConcept(_m))
	return &ConceptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ConceptClient) UpdateOneID(id uuid.UUID) *ConceptUpdateOne {
	mutation := newConceptMutation(c.config, OpUpdateOne, withConceptID(id))
	return &ConceptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Concept.
func (c *ConceptClient) Delete() *ConceptDelete {
	mutation := newConceptMutation(c.config, OpDelete)
	return &ConceptDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ConceptClient) DeleteOne(_m *Concept) *ConceptDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ConceptClient) DeleteOneID(id uuid.UUID) *ConceptDeleteOne {
	builder := c.Delete().Where(concept.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ConceptDeleteOne{builder}
}

// Query returns a query builder for Concept.
func (c *ConceptClient) Query() *ConceptQuery {
	return &ConceptQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeConcept},
		inters: c.Interceptors(),
	}
}

// Get returns a Concept entity by its id.
func (c *ConceptClient) Get(ctx context.Context, id uuid.UUID) (*Concept, error) {
	return c.Query().Where(concept.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ConceptClient) GetX(ctx context.Context, id uuid.UUID) *Concept {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProjects queries the projects edge of a Concept.
func (c *ConceptClient) QueryProjects(_m *Concept) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(concept.Table, concept.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, concept.ProjectsTable, concept.ProjectsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTutorialContents queries the tutorial_contents edge of a Concept.
func (c *ConceptClient) QueryTutorialContents(_m *Concept) *TutorialContentQuery {
	query := (&TutorialContentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(concept.Table, concept.FieldID, id),
			sqlgraph.To(tutorialcontent.Table, tutorialcontent.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, concept.TutorialContentsTable, concept.TutorialContentsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChildRelations queries the child_relations edge of a Concept.
func (c *ConceptClient) QueryChildRelations(_m *Concept) *ConceptRelationshipQuery {
	query := (&ConceptRelationshipClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(concept.Table, concept.FieldID, id),
			sqlgraph.To(conceptrelationship.Table, conceptrelationship.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, concept.ChildRelationsTable, concept.ChildRelationsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryParentRelations queries the parent_relations edge of a Concept.
func (c *ConceptClient) QueryParentRelations(_m *Concept) *ConceptRelationshipQuery {
	query := (&ConceptRelationshipClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(concept.Table, concept.FieldID, id),
			sqlgraph.To(conceptrelationship.Table, conceptrelationship.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, concept.ParentRelationsTable, concept.ParentRelationsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryProjectConcepts queries the project_concepts edge of a Concept.
func (c *ConceptClient) QueryProjectConcepts(_m *Concept) *ProjectConceptQuery {
	query := (&ProjectConceptClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(concept.Table, concept.FieldID, id),
			sqlgraph.To(projectconcept.Table, projectconcept.ConceptColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, concept.ProjectConceptsTable, concept.ProjectConceptsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTutorialConcepts queries the tutorial_concepts edge of a Concept.
func (c *ConceptClient) QueryTutorialConcepts(_m *Concept) *TutorialConceptQuery {
	query := (&TutorialConceptClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(concept.Table, concept.FieldID, id),
			sqlgraph.To(tutorialconcept.Table, tutorialconcept.ConceptColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, concept.TutorialConceptsTable, concept.TutorialConceptsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ConceptClient) Hooks() []Hook {
	return c.hooks.Concept
}

// Interceptors returns the client interceptors.
func (c *ConceptClient) Interceptors() []Interceptor {
	return c.inters.Concept
}

func (c *ConceptClient) mutate(ctx context.Context, m *ConceptMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ConceptCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ConceptUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ConceptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ConceptDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Concept mutation op: %q", m.Op())
	}
}

// ConceptRelationshipClient is a client for the ConceptRelationship schema.
type ConceptRelationshipClient struct {
	config
}

// NewConceptRelationshipClient returns a client for the ConceptRelationship from the given config.
func NewConceptRelationshipClient(c config) *ConceptRelationshipClient {
	return &ConceptRelationshipClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `conceptrelationship.Hooks(f(g(h())))`.
func (c *ConceptRelationshipClient) Use(hooks ...Hook) {
	c.hooks.ConceptRelationship = append(c.hooks.ConceptRelationship, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `conceptrelationship.Intercept(f(g(h())))`.
func (c *ConceptRelationshipClient) Intercept(interceptors ...Interceptor) {
	c.inters.ConceptRelationship = append(c.inters.ConceptRelationship, interceptors...)
}

// Create returns a builder for creating a ConceptRelationship entity.
func (c *ConceptRelationshipClient) Create() *ConceptRelationshipCreate {
	mutation := newConceptRelationshipMutation(c.config, OpCreate)
	return &ConceptRelationshipCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ConceptRelationship entities.
func (c *ConceptRelationshipClient) CreateBulk(builders ...*ConceptRelationshipCreate) *ConceptRelationshipCreateBulk {
	return &ConceptRelationshipCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ConceptRelationshipClient) MapCreateBulk(slice any, setFunc func(*ConceptRelationshipCreate, int)) *ConceptRelationshipCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ConceptRelationshipCreateBulk{err: fmt.Errorf("calling to ConceptRelationshipClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ConceptRelationshipCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ConceptRelationshipCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ConceptRelationship.
func (c *ConceptRelationshipClient) Update() *ConceptRelationshipUpdate {
	mutation := newConceptRelationshipMutation(c.config, OpUpdate)
	return &ConceptRelationshipUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ConceptRelationshipClient) UpdateOne(_m *ConceptRelationship) *ConceptRelationshipUpdateOne {
	mutation := newConceptRelationshipMutation(c.config, OpUpdateOne, withConceptRelationship(_m))
	return &ConceptRelationshipUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ConceptRelationshipClient) UpdateOneID(id uuid.UUID) *ConceptRelationshipUpdateOne {
	mutation := newConceptRelationshipMutation(c.config, OpUpdateOne, withConceptRelationshipID(id))
	return &ConceptRelationshipUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ConceptRelationship.
func (c *ConceptRelationshipClient) Delete() *ConceptRelationshipDelete {
	mutation := newConceptRelationshipMutation(c.config, OpDelete)
	return &ConceptRelationshipDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ConceptRelationshipClient) DeleteOne(_m *ConceptRelationship) *ConceptRelationshipDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ConceptRelationshipClient) DeleteOneID(id uuid.UUID) *ConceptRelationshipDeleteOne {
	builder := c.Delete().Where(conceptrelationship.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ConceptRelationshipDeleteOne{builder}
}

// Query returns a query builder for ConceptRelationship.
func (c *ConceptRelationshipClient) Query() *ConceptRelationshipQuery {
	return &ConceptRelationshipQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeConceptRelationship},
		inters: c.Interceptors(),
	}
}

// Get returns a ConceptRelationship entity by its id.
func (c *ConceptRelationshipClient) Get(ctx context.Context, id uuid.UUID) (*ConceptRelationship, error) {
	return c.Query().Where(conceptrelationship.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ConceptRelationshipClient) GetX(ctx context.Context, id uuid.UUID) *ConceptRelationship {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryParent queries the parent edge of a ConceptRelationship.
func (c *ConceptRelationshipClient) QueryParent(_m *ConceptRelationship) *ConceptQuery {
	query := (&ConceptClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(conceptrelationship.Table, conceptrelationship.FieldID, id),
			sqlgraph.To(concept.Table, concept.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, conceptrelationship.ParentTable, conceptrelationship.ParentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryChild queries the child edge of a ConceptRelationship.
func (c *ConceptRelationshipClient) QueryChild(_m *ConceptRelationship) *ConceptQuery {
	query := (&ConceptClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(conceptrelationship.Table, conceptrelationship.FieldID, id),
			sqlgraph.To(concept.Table, concept.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, conceptrelationship.ChildTable, conceptrelationship.ChildColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ConceptRelationshipClient) Hooks() []Hook {
	return c.hooks.ConceptRelationship
}

// Interceptors returns the client interceptors.
func (c *ConceptRelationshipClient) Interceptors() []Interceptor {
	return c.inters.ConceptRelationship
}

func (c *ConceptRelationshipClient) mutate(ctx context.Context, m *ConceptRelationshipMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ConceptRelationshipCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ConceptRelationshipUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ConceptRelationshipUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ConceptRelationshipDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ConceptRelationship mutation op: %q", m.Op())
	}
}

// GithubIssueClient is a client for the GithubIssue schema.
type GithubIssueClient struct {
	config
}

// NewGithubIssueClient returns a client for the GithubIssue from the given config.
func NewGithubIssueClient(c config) *GithubIssueClient {
	return &GithubIssueClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `githubissue.Hooks(f(g(h())))`.
func (c *GithubIssueClient) Use(hooks ...Hook) {
	c.hooks.GithubIssue = append(c.hooks.GithubIssue, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `githubissue.Intercept(f(g(h())))`.
func (c *GithubIssueClient) Intercept(interceptors ...Interceptor) {
	c.inters.GithubIssue = append(c.inters.GithubIssue, interceptors...)
}

// Create returns a builder for creating a GithubIssue entity.
func (c *GithubIssueClient) Create() *GithubIssueCreate {
	mutation := newGithubIssueMutation(c.config, OpCreate)
	return &GithubIssueCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GithubIssue entities.
func (c *GithubIssueClient) CreateBulk(builders ...*GithubIssueCreate) *GithubIssueCreateBulk {
	return &GithubIssueCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GithubIssueClient) MapCreateBulk(slice any, setFunc func(*GithubIssueCreate, int)) *GithubIssueCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GithubIssueCreateBulk{err: fmt.Errorf("calling to GithubIssueClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GithubIssueCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GithubIssueCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GithubIssue.
func (c *GithubIssueClient) Update() *GithubIssueUpdate {
	mutation := newGithubIssueMutation(c.config, OpUpdate)
	return &GithubIssueUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GithubIssueClient) UpdateOne(_m *GithubIssue) *GithubIssueUpdateOne {
	mutation := newGithubIssueMutation(c.config, OpUpdateOne, withGithubIssue(_m))
	return &GithubIssueUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GithubIssueClient) UpdateOneID(id uuid.UUID) *GithubIssueUpdateOne {
	mutation := newGithubIssueMutation(c.config, OpUpdateOne, withGithubIssueID(id))
	return &GithubIssueUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GithubIssue.
func (c *GithubIssueClient) Delete() *GithubIssueDelete {
	mutation := newGithubIssueMutation(c.config, OpDelete)
	return &GithubIssueDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GithubIssueClient) DeleteOne(_m *GithubIssue) *GithubIssueDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GithubIssueClient) DeleteOneID(id uuid.UUID) *GithubIssueDeleteOne {
	builder := c.Delete().Where(githubissue.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GithubIssueDeleteOne{builder}
}

// Query returns a query builder for GithubIssue.
func (c *GithubIssueClient) Query() *GithubIssueQuery {
	return &GithubIssueQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGithubIssue},
		inters: c.Interceptors(),
	}
}

// Get returns a GithubIssue entity by its id.
func (c *GithubIssueClient) Get(ctx context.Context, id uuid.UUID) (*GithubIssue, error) {
	return c.Query().Where(githubissue.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GithubIssueClient) GetX(ctx context.Context, id uuid.UUID) *GithubIssue {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryProject queries the project edge of a GithubIssue.
func (c *GithubIssueClient) QueryProject(_m *GithubIssue) *ProjectQuery {
	query := (&ProjectClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(githubissue.Table, githubissue.FieldID, id),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, githubissue.ProjectTable, githubissue.ProjectColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTutorialContent queries the tutorial_content edge of a GithubIssue.
func (c *GithubIssueClient) QueryTutorialContent(_m *GithubIssue) *TutorialContentQuery {
	query := (&TutorialContentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(githubissue.Table, githubissue.FieldID, id),
			sqlgraph.To(tutorialcontent.Table, tutorialcontent.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, githubissue.TutorialContentTable, githubissue.TutorialContentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *GithubIssueClient) Hooks() []Hook {
	return c.hooks.GithubIssue
}

// Interceptors returns the client interceptors.
func (c *GithubIssueClient) Interceptors() []Interceptor {
	return c.inters.GithubIssue
}

func (c *GithubIssueClient) mutate(ctx context.Context, m *GithubIssueMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GithubIssueCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GithubIssueUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GithubIssueUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GithubIssueDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GithubIssue mutation op: %q", m.Op())
	}
}

// ProjectClient is a client for the Project schema.
type ProjectClient struct {
	config
}

// NewProjectClient returns a client for the Project from the given config.
func NewProjectClient(c config) *ProjectClient {
	return &ProjectClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `project.Hooks(f(g(h())))`.
func (c *ProjectClient) Use(hooks ...Hook) {
	c.hooks.Project = append(c.hooks.Project, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `project.Intercept(f(g(h())))`.
func (c *ProjectClient) Intercept(interceptors ...Interceptor) {
	c.inters.Project = append(c.inters.Project, interceptors...)
}

// Create returns a builder for creating a Project entity.
func (c *ProjectClient) Create() *ProjectCreate {
	mutation := newProjectMutation(c.config, OpCreate)
	return &ProjectCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Project entities.
func (c *ProjectClient) CreateBulk(builders ...*ProjectCreate) *ProjectCreateBulk {
	return &ProjectCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProjectClient) MapCreateBulk(slice any, setFunc func(*ProjectCreate, int)) *ProjectCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProjectCreateBulk{err: fmt.Errorf("calling to ProjectClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProjectCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProjectCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Project.
func (c *ProjectClient) Update() *ProjectUpdate {
	mutation := newProjectMutation(c.config, OpUpdate)
	return &ProjectUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProjectClient) UpdateOne(_m *Project) *ProjectUpdateOne {
	mutation := newProjectMutation(c.config, OpUpdateOne, withProject(_m))
	return &ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProjectClient) UpdateOneID(id uuid.UUID) *ProjectUpdateOne {
	mutation := newProjectMutation(c.config, OpUpdateOne, withProjectID(id))
	return &ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Project.
func (c *ProjectClient) Delete() *ProjectDelete {
	mutation := newProjectMutation(c.config, OpDelete)
	return &ProjectDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProjectClient) DeleteOne(_m *Project) *ProjectDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProjectClient) DeleteOneID(id uuid.UUID) *ProjectDeleteOne {
	builder := c.Delete().Where(project.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProjectDeleteOne{builder}
}

// Query returns a query builder for Project.
func (c *ProjectClient) Query() *ProjectQuery {
	return &ProjectQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProject},
		inters: c.Interceptors(),
	}
}

// Get returns a Project entity by its id.
func (c *ProjectClient) Get(ctx context.Context, id uuid.UUID) (*Project, error) {
	return c.Query().Where(project.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProjectClient) GetX(ctx context.Context, id uuid.UUID) *Project {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryIssues queries the issues edge of a Project.
func (c *ProjectClient) QueryIssues(_m *Project) *GithubIssueQuery {
	query := (&GithubIssueClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(project.Table, project.FieldID, id),
			sqlgraph.To(githubissue.Table, githubissue.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, project.IssuesTable, project.IssuesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryConcepts queries the concepts edge of a Project.
func (c *ProjectClient) QueryConcepts(_m *Project) *ConceptQuery {
	query := (&ConceptClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(project.Table, project.FieldID, id),
			sqlgraph.To(concept.Table, concept.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, project.ConceptsTable, project.ConceptsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryProjectConcepts queries the project_concepts edge of a Project.
func (c *ProjectClient) QueryProjectConcepts(_m *Project) *ProjectConceptQuery {
	query := (&ProjectConceptClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(project.Table, project.FieldID, id),
			sqlgraph.To(projectconcept.Table, projectconcept.ProjectColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, project.ProjectConceptsTable, project.ProjectConceptsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ProjectClient) Hooks() []Hook {
	return c.hooks.Project
}

// Interceptors returns the client interceptors.
func (c *ProjectClient) Interceptors() []Interceptor {
	return c.inters.Project
}

func (c *ProjectClient) mutate(ctx context.Context, m *ProjectMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProjectCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProjectUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProjectUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProjectDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Project mutation op: %q", m.Op())
	}
}

// ProjectConceptClient is a client for the ProjectConcept schema.
type ProjectConceptClient struct {
	config
}

// NewProjectConceptClient returns a client for the ProjectConcept from the given config.
func NewProjectConceptClient(c config) *ProjectConceptClient {
	return &ProjectConceptClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `projectconcept.Hooks(f(g(h())))`.
func (c *ProjectConceptClient) Use(hooks ...Hook) {
	c.hooks.ProjectConcept = append(c.hooks.ProjectConcept, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `projectconcept.Intercept(f(g(h())))`.
func (c *ProjectConceptClient) Intercept(interceptors ...Interceptor) {
	c.inters.ProjectConcept = append(c.inters.ProjectConcept, interceptors...)
}

// Create returns a builder for creating a ProjectConcept entity.
func (c *ProjectConceptClient) Create() *ProjectConceptCreate {
	mutation := newProjectConceptMutation(c.config, OpCreate)
	return &ProjectConceptCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ProjectConcept entities.
func (c *ProjectConceptClient) CreateBulk(builders ...*ProjectConceptCreate) *ProjectConceptCreateBulk {
	return &ProjectConceptCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProjectConceptClient) MapCreateBulk(slice any, setFunc func(*ProjectConceptCreate, int)) *ProjectConceptCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProjectConceptCreateBulk{err: fmt.Errorf("calling to ProjectConceptClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProjectConceptCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProjectConceptCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ProjectConcept.
func (c *ProjectConceptClient) Update() *ProjectConceptUpdate {
	mutation := newProjectConceptMutation(c.config, OpUpdate)
	return &ProjectConceptUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProjectConceptClient) UpdateOne(_m *ProjectConcept) *ProjectConceptUpdateOne {
	mutation := newProjectConceptMutation(c.config, OpUpdateOne)
	mutation.project = &_m.ProjectID
	mutation.concept = &_m.ConceptID
	return &ProjectConceptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ProjectConcept.
func (c *ProjectConceptClient) Delete() *ProjectConceptDelete {
	mutation := newProjectConceptMutation(c.config, OpDelete)
	return &ProjectConceptDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Query returns a query builder for ProjectConcept.
func (c *ProjectConceptClient) Query() *ProjectConceptQuery {
	return &ProjectConceptQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProjectConcept},
		inters: c.Interceptors(),
	}
}

// QueryProject queries the project edge of a ProjectConcept.
func (c *ProjectConceptClient) QueryProject(_m *ProjectConcept) *ProjectQuery {
	return c.Query().
		Where(projectconcept.ProjectID(_m.ProjectID), projectconcept.ConceptID(_m.ConceptID)).
		QueryProject()
}

// QueryConcept queries the concept edge of a ProjectConcept.
func (c *ProjectConceptClient) QueryConcept(_m *ProjectConcept) *ConceptQuery {
	return c.Query().
		Where(projectconcept.ProjectID(_m.ProjectID), projectconcept.ConceptID(_m.ConceptID)).
		QueryConcept()
}

// Hooks returns the client hooks.
func (c *ProjectConceptClient) Hooks() []Hook {
	return c.hooks.ProjectConcept
}

// Interceptors returns the client interceptors.
func (c *ProjectConceptClient) Interceptors() []Interceptor {
	return c.inters.ProjectConcept
}

func (c *ProjectConceptClient) mutate(ctx context.Context, m *ProjectConceptMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProjectConceptCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProjectConceptUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProjectConceptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProjectConceptDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ProjectConcept mutation op: %q", m.Op())
	}
}

// TutorialClient is a client for the Tutorial schema.
type TutorialClient struct {
	config
}

// NewTutorialClient returns a client for the Tutorial from the given config.
func NewTutorialClient(c config) *TutorialClient {
	return &TutorialClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tutorial.Hooks(f(g(h())))`.
func (c *TutorialClient) Use(hooks ...Hook) {
	c.hooks.Tutorial = append(c.hooks.Tutorial, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tutorial.Intercept(f(g(h())))`.
func (c *TutorialClient) Intercept(interceptors ...Interceptor) {
	c.inters.Tutorial = append(c.inters.Tutorial, interceptors...)
}

// Create returns a builder for creating a Tutorial entity.
func (c *TutorialClient) Create() *TutorialCreate {
	mutation := newTutorialMutation(c.config, OpCreate)
	return &TutorialCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tutorial entities.
func (c *TutorialClient) CreateBulk(builders ...*TutorialCreate) *TutorialCreateBulk {
	return &TutorialCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TutorialClient) MapCreateBulk(slice any, setFunc func(*TutorialCreate, int)) *TutorialCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TutorialCreateBulk{err: fmt.Errorf("calling to TutorialClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TutorialCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TutorialCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tutorial.
func (c *TutorialClient) Update() *TutorialUpdate {
	mutation := newTutorialMutation(c.config, OpUpdate)
	return &TutorialUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TutorialClient) UpdateOne(_m *Tutorial) *TutorialUpdateOne {
	mutation := newTutorialMutation(c.config, OpUpdateOne, withTutorial(_m))
	return &TutorialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TutorialClient) UpdateOneID(id uuid.UUID) *TutorialUpdateOne {
	mutation := newTutorialMutation(c.config, OpUpdateOne, withTutorialID(id))
	return &TutorialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tutorial.
func (c *TutorialClient) Delete() *TutorialDelete {
	mutation := newTutorialMutation(c.config, OpDelete)
	return &TutorialDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TutorialClient) DeleteOne(_m *Tutorial) *TutorialDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TutorialClient) DeleteOneID(id uuid.UUID) *TutorialDeleteOne {
	builder := c.Delete().Where(tutorial.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TutorialDeleteOne{builder}
}

// Query returns a query builder for Tutorial.
func (c *TutorialClient) Query() *TutorialQuery {
	return &TutorialQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTutorial},
		inters: c.Interceptors(),
	}
}

// Get returns a Tutorial entity by its id.
func (c *TutorialClient) Get(ctx context.Context, id uuid.UUID) (*Tutorial, error) {
	return c.Query().Where(tutorial.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TutorialClient) GetX(ctx context.Context, id uuid.UUID) *Tutorial {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a Tutorial.
func (c *TutorialClient) QueryUser(_m *Tutorial) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tutorial.Table, tutorial.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tutorial.UserTable, tutorial.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryContent queries the content edge of a Tutorial.
func (c *TutorialClient) QueryContent(_m *Tutorial) *TutorialContentQuery {
	query := (&TutorialContentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tutorial.Table, tutorial.FieldID, id),
			sqlgraph.To(tutorialcontent.Table, tutorialcontent.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tutorial.ContentTable, tutorial.ContentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TutorialClient) Hooks() []Hook {
	return c.hooks.Tutorial
}

// Interceptors returns the client interceptors.
func (c *TutorialClient) Interceptors() []Interceptor {
	return c.inters.Tutorial
}

func (c *TutorialClient) mutate(ctx context.Context, m *TutorialMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TutorialCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TutorialUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TutorialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TutorialDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tutorial mutation op: %q", m.Op())
	}
}

// TutorialConceptClient is a client for the TutorialConcept schema.
type TutorialConceptClient struct {
	config
}

// NewTutorialConceptClient returns a client for the TutorialConcept from the given config.
func NewTutorialConceptClient(c config) *TutorialConceptClient {
	return &TutorialConceptClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tutorialconcept.Hooks(f(g(h())))`.
func (c *TutorialConceptClient) Use(hooks ...Hook) {
	c.hooks.TutorialConcept = append(c.hooks.TutorialConcept, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tutorialconcept.Intercept(f(g(h())))`.
func (c *TutorialConceptClient) Intercept(interceptors ...Interceptor) {
	c.inters.TutorialConcept = append(c.inters.TutorialConcept, interceptors...)
}

// Create returns a builder for creating a TutorialConcept entity.
func (c *TutorialConceptClient) Create() *TutorialConceptCreate {
	mutation := newTutorialConceptMutation(c.config, OpCreate)
	return &TutorialConceptCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TutorialConcept entities.
func (c *TutorialConceptClient) CreateBulk(builders ...*TutorialConceptCreate) *TutorialConceptCreateBulk {
	return &TutorialConceptCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TutorialConceptClient) MapCreateBulk(slice any, setFunc func(*TutorialConceptCreate, int)) *TutorialConceptCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TutorialConceptCreateBulk{err: fmt.Errorf("calling to TutorialConceptClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TutorialConceptCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TutorialConceptCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TutorialConcept.
func (c *TutorialConceptClient) Update() *TutorialConceptUpdate {
	mutation := newTutorialConceptMutation(c.config, OpUpdate)
	return &TutorialConceptUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TutorialConceptClient) UpdateOne(_m *TutorialConcept) *TutorialConceptUpdateOne {
	mutation := newTutorialConceptMutation(c.config, OpUpdateOne)
	mutation.content = &_m.ContentID
	mutation.concept = &_m.ConceptID
	return &TutorialConceptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TutorialConcept.
func (c *TutorialConceptClient) Delete() *TutorialConceptDelete {
	mutation := newTutorialConceptMutation(c.config, OpDelete)
	return &TutorialConceptDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Query returns a query builder for TutorialConcept.
func (c *TutorialConceptClient) Query() *TutorialConceptQuery {
	return &TutorialConceptQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTutorialConcept},
		inters: c.Interceptors(),
	}
}

// QueryContent queries the content edge of a TutorialConcept.
func (c *TutorialConceptClient) QueryContent(_m *TutorialConcept) *TutorialContentQuery {
	return c.Query().
		Where(tutorialconcept.ContentID(_m.ContentID), tutorialconcept.ConceptID(_m.ConceptID)).
		QueryContent()
}

// QueryConcept queries the concept edge of a TutorialConcept.
func (c *TutorialConceptClient) QueryConcept(_m *TutorialConcept) *ConceptQuery {
	return c.Query().
		Where(tutorialconcept.ContentID(_m.ContentID), tutorialconcept.ConceptID(_m.ConceptID)).
		QueryConcept()
}

// Hooks returns the client hooks.
func (c *TutorialConceptClient) Hooks() []Hook {
	return c.hooks.TutorialConcept
}

// Interceptors returns the client interceptors.
func (c *TutorialConceptClient) Interceptors() []Interceptor {
	return c.inters.TutorialConcept
}

func (c *TutorialConceptClient) mutate(ctx context.Context, m *TutorialConceptMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TutorialConceptCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TutorialConceptUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TutorialConceptUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TutorialConceptDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TutorialConcept mutation op: %q", m.Op())
	}
}

// TutorialContentClient is a client for the TutorialContent schema.
type TutorialContentClient struct {
	config
}

// NewTutorialContentClient returns a client for the TutorialContent from the given config.
func NewTutorialContentClient(c config) *TutorialContentClient {
	return &TutorialContentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tutorialcontent.Hooks(f(g(h())))`.
func (c *TutorialContentClient) Use(hooks ...Hook) {
	c.hooks.TutorialContent = append(c.hooks.TutorialContent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tutorialcontent.Intercept(f(g(h())))`.
func (c *TutorialContentClient) Intercept(interceptors ...Interceptor) {
	c.inters.TutorialContent = append(c.inters.TutorialContent, interceptors...)
}

// Create returns a builder for creating a TutorialContent entity.
func (c *TutorialContentClient) Create() *TutorialContentCreate {
	mutation := newTutorialContentMutation(c.config, OpCreate)
	return &TutorialContentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TutorialContent entities.
func (c *TutorialContentClient) CreateBulk(builders ...*TutorialContentCreate) *TutorialContentCreateBulk {
	return &TutorialContentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TutorialContentClient) MapCreateBulk(slice any, setFunc func(*TutorialContentCreate, int)) *TutorialContentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TutorialContentCreateBulk{err: fmt.Errorf("calling to TutorialContentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TutorialContentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TutorialContentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TutorialContent.
func (c *TutorialContentClient) Update() *TutorialContentUpdate {
	mutation := newTutorialContentMutation(c.config, OpUpdate)
	return &TutorialContentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TutorialContentClient) UpdateOne(_m *TutorialContent) *TutorialContentUpdateOne {
	mutation := newTutorialContentMutation(c.config, OpUpdateOne, withTutorialContent(_m))
	return &TutorialContentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TutorialContentClient) UpdateOneID(id uuid.UUID) *TutorialContentUpdateOne {
	mutation := newTutorialContentMutation(c.config, OpUpdateOne, withTutorialContentID(id))
	return &TutorialContentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TutorialContent.
func (c *TutorialContentClient) Delete() *TutorialContentDelete {
	mutation := newTutorialContentMutation(c.config, OpDelete)
	return &TutorialContentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TutorialContentClient) DeleteOne(_m *TutorialContent) *TutorialContentDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TutorialContentClient) DeleteOneID(id uuid.UUID) *TutorialContentDeleteOne {
	builder := c.Delete().Where(tutorialcontent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TutorialContentDeleteOne{builder}
}

// Query returns a query builder for TutorialContent.
func (c *TutorialContentClient) Query() *TutorialContentQuery {
	return &TutorialContentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTutorialContent},
		inters: c.Interceptors(),
	}
}

// Get returns a TutorialContent entity by its id.
func (c *TutorialContentClient) Get(ctx context.Context, id uuid.UUID) (*TutorialContent, error) {
	return c.Query().Where(tutorialcontent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TutorialContentClient) GetX(ctx context.Context, id uuid.UUID) *TutorialContent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryIssue queries the issue edge of a TutorialContent.
func (c *TutorialContentClient) QueryIssue(_m *TutorialContent) *GithubIssueQuery {
	query := (&GithubIssueClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tutorialcontent.Table, tutorialcontent.FieldID, id),
			sqlgraph.To(githubissue.Table, githubissue.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, tutorialcontent.IssueTable, tutorialcontent.IssueColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTutorials queries the tutorials edge of a TutorialContent.
func (c *TutorialContentClient) QueryTutorials(_m *TutorialContent) *TutorialQuery {
	query := (&TutorialClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tutorialcontent.Table, tutorialcontent.FieldID, id),
			sqlgraph.To(tutorial.Table, tutorial.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tutorialcontent.TutorialsTable, tutorialcontent.TutorialsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryConcepts queries the concepts edge of a TutorialContent.
func (c *TutorialContentClient) QueryConcepts(_m *TutorialContent) *ConceptQuery {
	query := (&ConceptClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tutorialcontent.Table, tutorialcontent.FieldID, id),
			sqlgraph.To(concept.Table, concept.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, tutorialcontent.ConceptsTable, tutorialcontent.ConceptsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTutorialConcepts queries the tutorial_concepts edge of a TutorialContent.
func (c *TutorialContentClient) QueryTutorialConcepts(_m *TutorialContent) *TutorialConceptQuery {
	query := (&TutorialConceptClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tutorialcontent.Table, tutorialcontent.FieldID, id),
			sqlgraph.To(tutorialconcept.Table, tutorialconcept.ContentColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, tutorialcontent.TutorialConceptsTable, tutorialcontent.TutorialConceptsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TutorialContentClient) Hooks() []Hook {
	return c.hooks.TutorialContent
}

// Interceptors returns the client interceptors.
func (c *TutorialContentClient) Interceptors() []Interceptor {
	return c.inters.TutorialContent
}

func (c *TutorialContentClient) mutate(ctx context.Context, m *TutorialContentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TutorialContentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TutorialContentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TutorialContentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TutorialContentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TutorialContent mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryIdentities queries the identities edge of a User.
func (c *UserClient) QueryIdentities(_m *User) *UserIdentityQuery {
	query := (&UserIdentityClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(useridentity.Table, useridentity.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.IdentitiesTable, user.IdentitiesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTutorials queries the tutorials edge of a User.
func (c *UserClient) QueryTutorials(_m *User) *TutorialQuery {
	query := (&TutorialClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(tutorial.Table, tutorial.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.TutorialsTable, user.TutorialsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// UserIdentityClient is a client for the UserIdentity schema.
type UserIdentityClient struct {
	config
}

// NewUserIdentityClient returns a client for the UserIdentity from the given config.
func NewUserIdentityClient(c config) *UserIdentityClient {
	return &UserIdentityClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `useridentity.Hooks(f(g(h())))`.
func (c *UserIdentityClient) Use(hooks ...Hook) {
	c.hooks.UserIdentity = append(c.hooks.UserIdentity, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `useridentity.Intercept(f(g(h())))`.
func (c *UserIdentityClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserIdentity = append(c.inters.UserIdentity, interceptors...)
}

// Create returns a builder for creating a UserIdentity entity.
func (c *UserIdentityClient) Create() *UserIdentityCreate {
	mutation := newUserIdentityMutation(c.config, OpCreate)
	return &UserIdentityCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserIdentity entities.
func (c *UserIdentityClient) CreateBulk(builders ...*UserIdentityCreate) *UserIdentityCreateBulk {
	return &UserIdentityCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserIdentityClient) MapCreateBulk(slice any, setFunc func(*UserIdentityCreate, int)) *UserIdentityCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserIdentityCreateBulk{err: fmt.Errorf("calling to UserIdentityClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserIdentityCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserIdentityCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserIdentity.
func (c *UserIdentityClient) Update() *UserIdentityUpdate {
	mutation := newUserIdentityMutation(c.config, OpUpdate)
	return &UserIdentityUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserIdentityClient) UpdateOne(_m *UserIdentity) *UserIdentityUpdateOne {
	mutation := newUserIdentityMutation(c.config, OpUpdateOne, withUserIdentity(_m))
	return &UserIdentityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserIdentityClient) UpdateOneID(id uuid.UUID) *UserIdentityUpdateOne {
	mutation := newUserIdentityMutation(c.config, OpUpdateOne, withUserIdentityID(id))
	return &UserIdentityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserIdentity.
func (c *UserIdentityClient) Delete() *UserIdentityDelete {
	mutation := newUserIdentityMutation(c.config, OpDelete)
	return &UserIdentityDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserIdentityClient) DeleteOne(_m *UserIdentity) *UserIdentityDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserIdentityClient) DeleteOneID(id uuid.UUID) *UserIdentityDeleteOne {
	builder := c.Delete().Where(useridentity.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserIdentityDeleteOne{builder}
}

// Query returns a query builder for UserIdentity.
func (c *UserIdentityClient) Query() *UserIdentityQuery {
	return &UserIdentityQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserIdentity},
		inters: c.Interceptors(),
	}
}

// Get returns a UserIdentity entity by its id.
func (c *UserIdentityClient) Get(ctx context.Context, id uuid.UUID) (*UserIdentity, error) {
	return c.Query().Where(useridentity.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserIdentityClient) GetX(ctx context.Context, id uuid.UUID) *UserIdentity {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUser queries the user edge of a UserIdentity.
func (c *UserIdentityClient) QueryUser(_m *UserIdentity) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(useridentity.Table, useridentity.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, useridentity.UserTable, useridentity.UserColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserIdentityClient) Hooks() []Hook {
	return c.hooks.UserIdentity
}

// Interceptors returns the client interceptors.
func (c *UserIdentityClient) Interceptors() []Interceptor {
	return c.inters.UserIdentity
}

func (c *UserIdentityClient) mutate(ctx context.Context, m *UserIdentityMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserIdentityCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserIdentityUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserIdentityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserIdentityDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserIdentity mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Concept, ConceptRelationship, GithubIssue, Project, ProjectConcept, Tutorial,
		TutorialConcept, TutorialContent, User, UserIdentity []ent.Hook
	}
	inters struct {
		Concept, ConceptRelationship, GithubIssue, Project, ProjectConcept, Tutorial,
		TutorialConcept, TutorialContent, User, UserIdentity []ent.Interceptor
	}
)
