// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/concept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/conceptrelationship"
	"github.com/issuesight/issuesight/internal/platform/db/ent/project"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialcontent"
)

// ConceptCreate is the builder for creating a Concept entity.
type ConceptCreate struct {
	config
	mutation *ConceptMutation
	hooks    []Hook
}

// SetSlug sets the "slug" field.
func (_c *ConceptCreate) SetSlug(v string) *ConceptCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ConceptCreate) SetName(v string) *ConceptCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ConceptCreate) SetDescription(v string) *ConceptCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ConceptCreate) SetNillableDescription(v *string) *ConceptCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *ConceptCreate) SetCategory(v string) *ConceptCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *ConceptCreate) SetNillableCategory(v *string) *ConceptCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetTutorialMarkdown sets the "tutorial_markdown" field.
func (_c *ConceptCreate) SetTutorialMarkdown(v string) *ConceptCreate {
	_c.mutation.SetTutorialMarkdown(v)
	return _c
}

// SetNillableTutorialMarkdown sets the "tutorial_markdown" field if the given value is not nil.
func (_c *ConceptCreate) SetNillableTutorialMarkdown(v *string) *ConceptCreate {
	if v != nil {
		_c.SetTutorialMarkdown(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ConceptCreate) SetID(v uuid.UUID) *ConceptCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ConceptCreate) SetNillableID(v *uuid.UUID) *ConceptCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddProjectIDs adds the "projects" edge to the Project entity by IDs.
func (_c *ConceptCreate) AddProjectIDs(ids ...uuid.UUID) *ConceptCreate {
	_c.mutation.AddProjectIDs(ids...)
	return _c
}

// AddProjects adds the "projects" edges to the Project entity.
func (_c *ConceptCreate) AddProjects(v ...*Project) *ConceptCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProjectIDs(ids...)
}

// AddTutorialContentIDs adds the "tutorial_contents" edge to the TutorialContent entity by IDs.
func (_c *ConceptCreate) AddTutorialContentIDs(ids ...uuid.UUID) *ConceptCreate {
	_c.mutation.AddTutorialContentIDs(ids...)
	return _c
}

// AddTutorialContents adds the "tutorial_contents" edges to the TutorialContent entity.
func (_c *ConceptCreate) AddTutorialContents(v ...*TutorialContent) *ConceptCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTutorialContentIDs(ids...)
}

// AddChildRelationIDs adds the "child_relations" edge to the ConceptRelationship entity by IDs.
func (_c *ConceptCreate) AddChildRelationIDs(ids ...uuid.UUID) *ConceptCreate {
	_c.mutation.AddChildRelationIDs(ids...)
	return _c
}

// AddChildRelations adds the "child_relations" edges to the ConceptRelationship entity.
func (_c *ConceptCreate) AddChildRelations(v ...*ConceptRelationship) *ConceptCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildRelationIDs(ids...)
}

// AddParentRelationIDs adds the "parent_relations" edge to the ConceptRelationship entity by IDs.
func (_c *ConceptCreate) AddParentRelationIDs(ids ...uuid.UUID) *ConceptCreate {
	_c.mutation.AddParentRelationIDs(ids...)
	return _c
}

// AddParentRelations adds the "parent_relations" edges to the ConceptRelationship entity.
func (_c *ConceptCreate) AddParentRelations(v ...*ConceptRelationship) *ConceptCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddParentRelationIDs(ids...)
}

// Mutation returns the ConceptMutation object of the builder.
func (_c *ConceptCreate) Mutation() *ConceptMutation {
	return _c.mutation
}

// Save creates the Concept in the database.
func (_c *ConceptCreate) Save(ctx context.Context) (*Concept, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConceptCreate) SaveX(ctx context.Context) *Concept {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConceptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConceptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConceptCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := concept.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConceptCreate) check() error {
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Concept.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := concept.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Concept.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Concept.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := concept.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Concept.name": %w`, err)}
		}
	}
	return nil
}

func (_c *ConceptCreate) sqlSave(ctx context.Context) (*Concept, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConceptCreate) createSpec() (*Concept, *sqlgraph.CreateSpec) {
	var (
		_node = &Concept{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(concept.Table, sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(concept.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(concept.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(concept.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(concept.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.TutorialMarkdown(); ok {
		_spec.SetField(concept.FieldTutorialMarkdown, field.TypeString, value)
		_node.TutorialMarkdown = value
	}
	if nodes := _c.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   concept.ProjectsTable,
			Columns: concept.ProjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TutorialContentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   concept.TutorialContentsTable,
			Columns: concept.TutorialContentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorialcontent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildRelationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   concept.ChildRelationsTable,
			Columns: []string{concept.ChildRelationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conceptrelationship.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentRelationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   concept.ParentRelationsTable,
			Columns: []string{concept.ParentRelationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conceptrelationship.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConceptCreateBulk is the builder for creating many Concept entities in bulk.
type ConceptCreateBulk struct {
	config
	err      error
	builders []*ConceptCreate
}

// Save creates the Concept entities in the database.
func (_c *ConceptCreateBulk) Save(ctx context.Context) ([]*Concept, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Concept, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConceptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConceptCreateBulk) SaveX(ctx context.Context) []*Concept {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConceptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConceptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
