// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/concept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/conceptrelationship"
	"github.com/issuesight/issuesight/internal/platform/db/ent/predicate"
	"github.com/issuesight/issuesight/internal/platform/db/ent/project"
	"github.com/issuesight/issuesight/internal/platform/db/ent/projectconcept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialconcept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialcontent"
)

// ConceptQuery is the builder for querying Concept entities.
type ConceptQuery struct {
	config
	ctx                  *QueryContext
	order                []concept.OrderOption
	inters               []Interceptor
	predicates           []predicate.Concept
	withProjects         *ProjectQuery
	withTutorialContents *TutorialContentQuery
	withChildRelations   *ConceptRelationshipQuery
	withParentRelations  *ConceptRelationshipQuery
	withProjectConcepts  *ProjectConceptQuery
	withTutorialConcepts *TutorialConceptQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ConceptQuery builder.
func (_q *ConceptQuery) Where(ps ...predicate.Concept) *ConceptQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ConceptQuery) Limit(limit int) *ConceptQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ConceptQuery) Offset(offset int) *ConceptQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ConceptQuery) Unique(unique bool) *ConceptQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ConceptQuery) Order(o ...concept.OrderOption) *ConceptQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProjects chains the current query on the "projects" edge.
func (_q *ConceptQuery) QueryProjects() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(concept.Table, concept.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, concept.ProjectsTable, concept.ProjectsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTutorialContents chains the current query on the "tutorial_contents" edge.
func (_q *ConceptQuery) QueryTutorialContents() *TutorialContentQuery {
	query := (&TutorialContentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(concept.Table, concept.FieldID, selector),
			sqlgraph.To(tutorialcontent.Table, tutorialcontent.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, concept.TutorialContentsTable, concept.TutorialContentsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChildRelations chains the current query on the "child_relations" edge.
func (_q *ConceptQuery) QueryChildRelations() *ConceptRelationshipQuery {
	query := (&ConceptRelationshipClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(concept.Table, concept.FieldID, selector),
			sqlgraph.To(conceptrelationship.Table, conceptrelationship.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, concept.ChildRelationsTable, concept.ChildRelationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParentRelations chains the current query on the "parent_relations" edge.
func (_q *ConceptQuery) QueryParentRelations() *ConceptRelationshipQuery {
	query := (&ConceptRelationshipClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(concept.Table, concept.FieldID, selector),
			sqlgraph.To(conceptrelationship.Table, conceptrelationship.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, concept.ParentRelationsTable, concept.ParentRelationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProjectConcepts chains the current query on the "project_concepts" edge.
func (_q *ConceptQuery) QueryProjectConcepts() *ProjectConceptQuery {
	query := (&ProjectConceptClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(concept.Table, concept.FieldID, selector),
			sqlgraph.To(projectconcept.Table, projectconcept.ConceptColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, concept.ProjectConceptsTable, concept.ProjectConceptsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTutorialConcepts chains the current query on the "tutorial_concepts" edge.
func (_q *ConceptQuery) QueryTutorialConcepts() *TutorialConceptQuery {
	query := (&TutorialConceptClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(concept.Table, concept.FieldID, selector),
			sqlgraph.To(tutorialconcept.Table, tutorialconcept.ConceptColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, concept.TutorialConceptsTable, concept.TutorialConceptsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Concept entity from the query.
// Returns a *NotFoundError when no Concept was found.
func (_q *ConceptQuery) First(ctx context.Context) (*Concept, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{concept.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ConceptQuery) FirstX(ctx context.Context) *Concept {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Concept ID from the query.
// Returns a *NotFoundError when no Concept ID was found.
func (_q *ConceptQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{concept.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ConceptQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Concept entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Concept entity is found.
// Returns a *NotFoundError when no Concept entities are found.
func (_q *ConceptQuery) Only(ctx context.Context) (*Concept, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{concept.Label}
	default:
		return nil, &NotSingularError{concept.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ConceptQuery) OnlyX(ctx context.Context) *Concept {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Concept ID in the query.
// Returns a *NotSingularError when more than one Concept ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ConceptQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{concept.Label}
	default:
		err = &NotSingularError{concept.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ConceptQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Concepts.
func (_q *ConceptQuery) All(ctx context.Context) ([]*Concept, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Concept, *ConceptQuery]()
	return withInterceptors[[]*Concept](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ConceptQuery) AllX(ctx context.Context) []*Concept {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Concept IDs.
func (_q *ConceptQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(concept.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ConceptQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ConceptQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ConceptQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ConceptQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ConceptQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ConceptQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ConceptQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ConceptQuery) Clone() *ConceptQuery {
	if _q == nil {
		return nil
	}
	return &ConceptQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]concept.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.Concept{}, _q.predicates...),
		withProjects:         _q.withProjects.Clone(),
		withTutorialContents: _q.withTutorialContents.Clone(),
		withChildRelations:   _q.withChildRelations.Clone(),
		withParentRelations:  _q.withParentRelations.Clone(),
		withProjectConcepts:  _q.withProjectConcepts.Clone(),
		withTutorialConcepts: _q.withTutorialConcepts.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProjects tells the query-builder to eager-load the nodes that are connected to
// the "projects" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ConceptQuery) WithProjects(opts ...func(*ProjectQuery)) *ConceptQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProjects = query
	return _q
}

// WithTutorialContents tells the query-builder to eager-load the nodes that are connected to
// the "tutorial_contents" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ConceptQuery) WithTutorialContents(opts ...func(*TutorialContentQuery)) *ConceptQuery {
	query := (&TutorialContentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTutorialContents = query
	return _q
}

// WithChildRelations tells the query-builder to eager-load the nodes that are connected to
// the "child_relations" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ConceptQuery) WithChildRelations(opts ...func(*ConceptRelationshipQuery)) *ConceptQuery {
	query := (&ConceptRelationshipClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChildRelations = query
	return _q
}

// WithParentRelations tells the query-builder to eager-load the nodes that are connected to
// the "parent_relations" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ConceptQuery) WithParentRelations(opts ...func(*ConceptRelationshipQuery)) *ConceptQuery {
	query := (&ConceptRelationshipClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withParentRelations = query
	return _q
}

// WithProjectConcepts tells the query-builder to eager-load the nodes that are connected to
// the "project_concepts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ConceptQuery) WithProjectConcepts(opts ...func(*ProjectConceptQuery)) *ConceptQuery {
	query := (&ProjectConceptClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProjectConcepts = query
	return _q
}

// WithTutorialConcepts tells the query-builder to eager-load the nodes that are connected to
// the "tutorial_concepts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ConceptQuery) WithTutorialConcepts(opts ...func(*TutorialConceptQuery)) *ConceptQuery {
	query := (&TutorialConceptClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTutorialConcepts = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Slug string `json:"slug,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Concept.Query().
//		GroupBy(concept.FieldSlug).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ConceptQuery) GroupBy(field string, fields ...string) *ConceptGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ConceptGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = concept.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Slug string `json:"slug,omitempty"`
//	}
//
//	client.Concept.Query().
//		Select(concept.FieldSlug).
//		Scan(ctx, &v)
func (_q *ConceptQuery) Select(fields ...string) *ConceptSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ConceptSelect{ConceptQuery: _q}
	sbuild.label = concept.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ConceptSelect configured with the given aggregations.
func (_q *ConceptQuery) Aggregate(fns ...AggregateFunc) *ConceptSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ConceptQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !concept.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ConceptQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Concept, error) {
	var (
		nodes       = []*Concept{}
		_spec       = _q.querySpec()
		loadedTypes = [6]bool{
			_q.withProjects != nil,
			_q.withTutorialContents != nil,
			_q.withChildRelations != nil,
			_q.withParentRelations != nil,
			_q.withProjectConcepts != nil,
			_q.withTutorialConcepts != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Concept).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Concept{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProjects; query != nil {
		if err := _q.loadProjects(ctx, query, nodes,
			func(n *Concept) { n.Edges.Projects = []*Project{} },
			func(n *Concept, e *Project) { n.Edges.Projects = append(n.Edges.Projects, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTutorialContents; query != nil {
		if err := _q.loadTutorialContents(ctx, query, nodes,
			func(n *Concept) { n.Edges.TutorialContents = []*TutorialContent{} },
			func(n *Concept, e *TutorialContent) { n.Edges.TutorialContents = append(n.Edges.TutorialContents, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChildRelations; query != nil {
		if err := _q.loadChildRelations(ctx, query, nodes,
			func(n *Concept) { n.Edges.ChildRelations = []*ConceptRelationship{} },
			func(n *Concept, e *ConceptRelationship) { n.Edges.ChildRelations = append(n.Edges.ChildRelations, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withParentRelations; query != nil {
		if err := _q.loadParentRelations(ctx, query, nodes,
			func(n *Concept) { n.Edges.ParentRelations = []*ConceptRelationship{} },
			func(n *Concept, e *ConceptRelationship) { n.Edges.ParentRelations = append(n.Edges.ParentRelations, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProjectConcepts; query != nil {
		if err := _q.loadProjectConcepts(ctx, query, nodes,
			func(n *Concept) { n.Edges.ProjectConcepts = []*ProjectConcept{} },
			func(n *Concept, e *ProjectConcept) { n.Edges.ProjectConcepts = append(n.Edges.ProjectConcepts, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTutorialConcepts; query != nil {
		if err := _q.loadTutorialConcepts(ctx, query, nodes,
			func(n *Concept) { n.Edges.TutorialConcepts = []*TutorialConcept{} },
			func(n *Concept, e *TutorialConcept) { n.Edges.TutorialConcepts = append(n.Edges.TutorialConcepts, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ConceptQuery) loadProjects(ctx context.Context, query *ProjectQuery, nodes []*Concept, init func(*Concept), assign func(*Concept, *Project)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*Concept)
	nids := make(map[uuid.UUID]map[*Concept]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(concept.ProjectsTable)
		s.Join(joinT).On(s.C(project.FieldID), joinT.C(concept.ProjectsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(concept.ProjectsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(concept.ProjectsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*Concept]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Project](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "projects" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *ConceptQuery) loadTutorialContents(ctx context.Context, query *TutorialContentQuery, nodes []*Concept, init func(*Concept), assign func(*Concept, *TutorialContent)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*Concept)
	nids := make(map[uuid.UUID]map[*Concept]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(concept.TutorialContentsTable)
		s.Join(joinT).On(s.C(tutorialcontent.FieldID), joinT.C(concept.TutorialContentsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(concept.TutorialContentsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(concept.TutorialContentsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*Concept]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*TutorialContent](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "tutorial_contents" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *ConceptQuery) loadChildRelations(ctx context.Context, query *ConceptRelationshipQuery, nodes []*Concept, init func(*Concept), assign func(*Concept, *ConceptRelationship)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Concept)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(conceptrelationship.FieldParentID)
	}
	query.Where(predicate.ConceptRelationship(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(concept.ChildRelationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ParentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "parent_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ConceptQuery) loadParentRelations(ctx context.Context, query *ConceptRelationshipQuery, nodes []*Concept, init func(*Concept), assign func(*Concept, *ConceptRelationship)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Concept)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(conceptrelationship.FieldChildID)
	}
	query.Where(predicate.ConceptRelationship(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(concept.ParentRelationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ChildID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "child_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ConceptQuery) loadProjectConcepts(ctx context.Context, query *ProjectConceptQuery, nodes []*Concept, init func(*Concept), assign func(*Concept, *ProjectConcept)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Concept)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(projectconcept.FieldConceptID)
	}
	query.Where(predicate.ProjectConcept(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(concept.ProjectConceptsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ConceptID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "concept_id" returned %v for node %v`, fk, n)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ConceptQuery) loadTutorialConcepts(ctx context.Context, query *TutorialConceptQuery, nodes []*Concept, init func(*Concept), assign func(*Concept, *TutorialConcept)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Concept)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(tutorialconcept.FieldConceptID)
	}
	query.Where(predicate.TutorialConcept(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(concept.TutorialConceptsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ConceptID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "concept_id" returned %v for node %v`, fk, n)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ConceptQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ConceptQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(concept.Table, concept.Columns, sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, concept.FieldID)
		for i := range fields {
			if fields[i] != concept.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ConceptQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(concept.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = concept.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ConceptGroupBy is the group-by builder for Concept entities.
type ConceptGroupBy struct {
	selector
	build *ConceptQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ConceptGroupBy) Aggregate(fns ...AggregateFunc) *ConceptGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ConceptGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ConceptQuery, *ConceptGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ConceptGroupBy) sqlScan(ctx context.Context, root *ConceptQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ConceptSelect is the builder for selecting fields of Concept entities.
type ConceptSelect struct {
	*ConceptQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ConceptSelect) Aggregate(fns ...AggregateFunc) *ConceptSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ConceptSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ConceptQuery, *ConceptSelect](ctx, _s.ConceptQuery, _s, _s.inters, v)
}

func (_s *ConceptSelect) sqlScan(ctx context.Context, root *ConceptQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
