// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/concept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/conceptrelationship"
)

// ConceptRelationship is the model entity for the ConceptRelationship schema.
type ConceptRelationship struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ParentID holds the value of the "parent_id" field.
	ParentID uuid.UUID `json:"parent_id,omitempty"`
	// ChildID holds the value of the "child_id" field.
	ChildID uuid.UUID `json:"child_id,omitempty"`
	// Relationship type, e.g. subconcept_of
	RelType string `json:"rel_type,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConceptRelationshipQuery when eager-loading is set.
	Edges        ConceptRelationshipEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ConceptRelationshipEdges holds the relations/edges for other nodes in the graph.
type ConceptRelationshipEdges struct {
	// Parent holds the value of the parent edge.
	Parent *Concept `json:"parent,omitempty"`
	// Child holds the value of the child edge.
	Child *Concept `json:"child,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConceptRelationshipEdges) ParentOrErr() (*Concept, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: concept.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildOrErr returns the Child value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConceptRelationshipEdges) ChildOrErr() (*Concept, error) {
	if e.Child != nil {
		return e.Child, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: concept.Label}
	}
	return nil, &NotLoadedError{edge: "child"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ConceptRelationship) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case conceptrelationship.FieldRelType:
			values[i] = new(sql.NullString)
		case conceptrelationship.FieldID, conceptrelationship.FieldParentID, conceptrelationship.FieldChildID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ConceptRelationship fields.
func (_m *ConceptRelationship) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case conceptrelationship.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case conceptrelationship.FieldParentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value != nil {
				_m.ParentID = *value
			}
		case conceptrelationship.FieldChildID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field child_id", values[i])
			} else if value != nil {
				_m.ChildID = *value
			}
		case conceptrelationship.FieldRelType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rel_type", values[i])
			} else if value.Valid {
				_m.RelType = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ConceptRelationship.
// This includes values selected through modifiers, order, etc.
func (_m *ConceptRelationship) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParent queries the "parent" edge of the ConceptRelationship entity.
func (_m *ConceptRelationship) QueryParent() *ConceptQuery {
	return NewConceptRelationshipClient(_m.config).QueryParent(_m)
}

// QueryChild queries the "child" edge of the ConceptRelationship entity.
func (_m *ConceptRelationship) QueryChild() *ConceptQuery {
	return NewConceptRelationshipClient(_m.config).QueryChild(_m)
}

// Update returns a builder for updating this ConceptRelationship.
// Note that you need to call ConceptRelationship.Unwrap() before calling this method if this ConceptRelationship
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ConceptRelationship) Update() *ConceptRelationshipUpdateOne {
	return NewConceptRelationshipClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ConceptRelationship entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ConceptRelationship) Unwrap() *ConceptRelationship {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ConceptRelationship is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ConceptRelationship) String() string {
	var builder strings.Builder
	builder.WriteString("ConceptRelationship(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("parent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentID))
	builder.WriteString(", ")
	builder.WriteString("child_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChildID))
	builder.WriteString(", ")
	builder.WriteString("rel_type=")
	builder.WriteString(_m.RelType)
	builder.WriteByte(')')
	return builder.String()
}

// ConceptRelationships is a parsable slice of ConceptRelationship.
type ConceptRelationships []*ConceptRelationship
