// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/githubissue"
	"github.com/issuesight/issuesight/internal/platform/db/ent/predicate"
	"github.com/issuesight/issuesight/internal/platform/db/ent/project"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialcontent"
)

// GithubIssueUpdate is the builder for updating GithubIssue entities.
type GithubIssueUpdate struct {
	config
	hooks    []Hook
	mutation *GithubIssueMutation
}

// Where appends a list predicates to the GithubIssueUpdate builder.
func (_u *GithubIssueUpdate) Where(ps ...predicate.GithubIssue) *GithubIssueUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *GithubIssueUpdate) SetProjectID(v uuid.UUID) *GithubIssueUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *GithubIssueUpdate) SetNillableProjectID(v *uuid.UUID) *GithubIssueUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetIssueNumber sets the "issue_number" field.
func (_u *GithubIssueUpdate) SetIssueNumber(v int) *GithubIssueUpdate {
	_u.mutation.ResetIssueNumber()
	_u.mutation.SetIssueNumber(v)
	return _u
}

// SetNillableIssueNumber sets the "issue_number" field if the given value is not nil.
func (_u *GithubIssueUpdate) SetNillableIssueNumber(v *int) *GithubIssueUpdate {
	if v != nil {
		_u.SetIssueNumber(*v)
	}
	return _u
}

// AddIssueNumber adds value to the "issue_number" field.
func (_u *GithubIssueUpdate) AddIssueNumber(v int) *GithubIssueUpdate {
	_u.mutation.AddIssueNumber(v)
	return _u
}

// SetGhIssueID sets the "gh_issue_id" field.
func (_u *GithubIssueUpdate) SetGhIssueID(v int64) *GithubIssueUpdate {
	_u.mutation.ResetGhIssueID()
	_u.mutation.SetGhIssueID(v)
	return _u
}

// SetNillableGhIssueID sets the "gh_issue_id" field if the given value is not nil.
func (_u *GithubIssueUpdate) SetNillableGhIssueID(v *int64) *GithubIssueUpdate {
	if v != nil {
		_u.SetGhIssueID(*v)
	}
	return _u
}

// AddGhIssueID adds value to the "gh_issue_id" field.
func (_u *GithubIssueUpdate) AddGhIssueID(v int64) *GithubIssueUpdate {
	_u.mutation.AddGhIssueID(v)
	return _u
}

// SetRawData sets the "raw_data" field.
func (_u *GithubIssueUpdate) SetRawData(v map[string]interface{}) *GithubIssueUpdate {
	_u.mutation.SetRawData(v)
	return _u
}

// ClearRawData clears the value of the "raw_data" field.
func (_u *GithubIssueUpdate) ClearRawData() *GithubIssueUpdate {
	_u.mutation.ClearRawData()
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *GithubIssueUpdate) SetLastSyncedAt(v time.Time) *GithubIssueUpdate {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *GithubIssueUpdate) SetNillableLastSyncedAt(v *time.Time) *GithubIssueUpdate {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *GithubIssueUpdate) SetProject(v *Project) *GithubIssueUpdate {
	return _u.SetProjectID(v.ID)
}

// SetTutorialContentID sets the "tutorial_content" edge to the TutorialContent entity by ID.
func (_u *GithubIssueUpdate) SetTutorialContentID(id uuid.UUID) *GithubIssueUpdate {
	_u.mutation.SetTutorialContentID(id)
	return _u
}

// SetNillableTutorialContentID sets the "tutorial_content" edge to the TutorialContent entity by ID if the given value is not nil.
func (_u *GithubIssueUpdate) SetNillableTutorialContentID(id *uuid.UUID) *GithubIssueUpdate {
	if id != nil {
		_u = _u.SetTutorialContentID(*id)
	}
	return _u
}

// SetTutorialContent sets the "tutorial_content" edge to the TutorialContent entity.
func (_u *GithubIssueUpdate) SetTutorialContent(v *TutorialContent) *GithubIssueUpdate {
	return _u.SetTutorialContentID(v.ID)
}

// Mutation returns the GithubIssueMutation object of the builder.
func (_u *GithubIssueUpdate) Mutation() *GithubIssueMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *GithubIssueUpdate) ClearProject() *GithubIssueUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearTutorialContent clears the "tutorial_content" edge to the TutorialContent entity.
func (_u *GithubIssueUpdate) ClearTutorialContent() *GithubIssueUpdate {
	_u.mutation.ClearTutorialContent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GithubIssueUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GithubIssueUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GithubIssueUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GithubIssueUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GithubIssueUpdate) check() error {
	if v, ok := _u.mutation.IssueNumber(); ok {
		if err := githubissue.IssueNumberValidator(v); err != nil {
			return &ValidationError{Name: "issue_number", err: fmt.Errorf(`ent: validator failed for field "GithubIssue.issue_number": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GithubIssue.project"`)
	}
	return nil
}

func (_u *GithubIssueUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(githubissue.Table, githubissue.Columns, sqlgraph.NewFieldSpec(githubissue.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IssueNumber(); ok {
		_spec.SetField(githubissue.FieldIssueNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIssueNumber(); ok {
		_spec.AddField(githubissue.FieldIssueNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GhIssueID(); ok {
		_spec.SetField(githubissue.FieldGhIssueID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGhIssueID(); ok {
		_spec.AddField(githubissue.FieldGhIssueID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RawData(); ok {
		_spec.SetField(githubissue.FieldRawData, field.TypeJSON, value)
	}
	if _u.mutation.RawDataCleared() {
		_spec.ClearField(githubissue.FieldRawData, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(githubissue.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   githubissue.ProjectTable,
			Columns: []string{githubissue.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   githubissue.ProjectTable,
			Columns: []string{githubissue.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TutorialContentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   githubissue.TutorialContentTable,
			Columns: []string{githubissue.TutorialContentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorialcontent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TutorialContentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   githubissue.TutorialContentTable,
			Columns: []string{githubissue.TutorialContentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorialcontent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{githubissue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GithubIssueUpdateOne is the builder for updating a single GithubIssue entity.
type GithubIssueUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GithubIssueMutation
}

// SetProjectID sets the "project_id" field.
func (_u *GithubIssueUpdateOne) SetProjectID(v uuid.UUID) *GithubIssueUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *GithubIssueUpdateOne) SetNillableProjectID(v *uuid.UUID) *GithubIssueUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetIssueNumber sets the "issue_number" field.
func (_u *GithubIssueUpdateOne) SetIssueNumber(v int) *GithubIssueUpdateOne {
	_u.mutation.ResetIssueNumber()
	_u.mutation.SetIssueNumber(v)
	return _u
}

// SetNillableIssueNumber sets the "issue_number" field if the given value is not nil.
func (_u *GithubIssueUpdateOne) SetNillableIssueNumber(v *int) *GithubIssueUpdateOne {
	if v != nil {
		_u.SetIssueNumber(*v)
	}
	return _u
}

// AddIssueNumber adds value to the "issue_number" field.
func (_u *GithubIssueUpdateOne) AddIssueNumber(v int) *GithubIssueUpdateOne {
	_u.mutation.AddIssueNumber(v)
	return _u
}

// SetGhIssueID sets the "gh_issue_id" field.
func (_u *GithubIssueUpdateOne) SetGhIssueID(v int64) *GithubIssueUpdateOne {
	_u.mutation.ResetGhIssueID()
	_u.mutation.SetGhIssueID(v)
	return _u
}

// SetNillableGhIssueID sets the "gh_issue_id" field if the given value is not nil.
func (_u *GithubIssueUpdateOne) SetNillableGhIssueID(v *int64) *GithubIssueUpdateOne {
	if v != nil {
		_u.SetGhIssueID(*v)
	}
	return _u
}

// AddGhIssueID adds value to the "gh_issue_id" field.
func (_u *GithubIssueUpdateOne) AddGhIssueID(v int64) *GithubIssueUpdateOne {
	_u.mutation.AddGhIssueID(v)
	return _u
}

// SetRawData sets the "raw_data" field.
func (_u *GithubIssueUpdateOne) SetRawData(v map[string]interface{}) *GithubIssueUpdateOne {
	_u.mutation.SetRawData(v)
	return _u
}

// ClearRawData clears the value of the "raw_data" field.
func (_u *GithubIssueUpdateOne) ClearRawData() *GithubIssueUpdateOne {
	_u.mutation.ClearRawData()
	return _u
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_u *GithubIssueUpdateOne) SetLastSyncedAt(v time.Time) *GithubIssueUpdateOne {
	_u.mutation.SetLastSyncedAt(v)
	return _u
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_u *GithubIssueUpdateOne) SetNillableLastSyncedAt(v *time.Time) *GithubIssueUpdateOne {
	if v != nil {
		_u.SetLastSyncedAt(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *GithubIssueUpdateOne) SetProject(v *Project) *GithubIssueUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetTutorialContentID sets the "tutorial_content" edge to the TutorialContent entity by ID.
func (_u *GithubIssueUpdateOne) SetTutorialContentID(id uuid.UUID) *GithubIssueUpdateOne {
	_u.mutation.SetTutorialContentID(id)
	return _u
}

// SetNillableTutorialContentID sets the "tutorial_content" edge to the TutorialContent entity by ID if the given value is not nil.
func (_u *GithubIssueUpdateOne) SetNillableTutorialContentID(id *uuid.UUID) *GithubIssueUpdateOne {
	if id != nil {
		_u = _u.SetTutorialContentID(*id)
	}
	return _u
}

// SetTutorialContent sets the "tutorial_content" edge to the TutorialContent entity.
func (_u *GithubIssueUpdateOne) SetTutorialContent(v *TutorialContent) *GithubIssueUpdateOne {
	return _u.SetTutorialContentID(v.ID)
}

// Mutation returns the GithubIssueMutation object of the builder.
func (_u *GithubIssueUpdateOne) Mutation() *GithubIssueMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *GithubIssueUpdateOne) ClearProject() *GithubIssueUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearTutorialContent clears the "tutorial_content" edge to the TutorialContent entity.
func (_u *GithubIssueUpdateOne) ClearTutorialContent() *GithubIssueUpdateOne {
	_u.mutation.ClearTutorialContent()
	return _u
}

// Where appends a list predicates to the GithubIssueUpdate builder.
func (_u *GithubIssueUpdateOne) Where(ps ...predicate.GithubIssue) *GithubIssueUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GithubIssueUpdateOne) Select(field string, fields ...string) *GithubIssueUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GithubIssue entity.
func (_u *GithubIssueUpdateOne) Save(ctx context.Context) (*GithubIssue, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GithubIssueUpdateOne) SaveX(ctx context.Context) *GithubIssue {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GithubIssueUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GithubIssueUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GithubIssueUpdateOne) check() error {
	if v, ok := _u.mutation.IssueNumber(); ok {
		if err := githubissue.IssueNumberValidator(v); err != nil {
			return &ValidationError{Name: "issue_number", err: fmt.Errorf(`ent: validator failed for field "GithubIssue.issue_number": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GithubIssue.project"`)
	}
	return nil
}

func (_u *GithubIssueUpdateOne) sqlSave(ctx context.Context) (_node *GithubIssue, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(githubissue.Table, githubissue.Columns, sqlgraph.NewFieldSpec(githubissue.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GithubIssue.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, githubissue.FieldID)
		for _, f := range fields {
			if !githubissue.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != githubissue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IssueNumber(); ok {
		_spec.SetField(githubissue.FieldIssueNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIssueNumber(); ok {
		_spec.AddField(githubissue.FieldIssueNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GhIssueID(); ok {
		_spec.SetField(githubissue.FieldGhIssueID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGhIssueID(); ok {
		_spec.AddField(githubissue.FieldGhIssueID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RawData(); ok {
		_spec.SetField(githubissue.FieldRawData, field.TypeJSON, value)
	}
	if _u.mutation.RawDataCleared() {
		_spec.ClearField(githubissue.FieldRawData, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastSyncedAt(); ok {
		_spec.SetField(githubissue.FieldLastSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   githubissue.ProjectTable,
			Columns: []string{githubissue.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   githubissue.ProjectTable,
			Columns: []string{githubissue.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TutorialContentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   githubissue.TutorialContentTable,
			Columns: []string{githubissue.TutorialContentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorialcontent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TutorialContentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   githubissue.TutorialContentTable,
			Columns: []string{githubissue.TutorialContentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorialcontent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GithubIssue{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{githubissue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
