// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/githubissue"
	"github.com/issuesight/issuesight/internal/platform/db/ent/project"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialcontent"
)

// GithubIssueCreate is the builder for creating a GithubIssue entity.
type GithubIssueCreate struct {
	config
	mutation *GithubIssueMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *GithubIssueCreate) SetProjectID(v uuid.UUID) *GithubIssueCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetIssueNumber sets the "issue_number" field.
func (_c *GithubIssueCreate) SetIssueNumber(v int) *GithubIssueCreate {
	_c.mutation.SetIssueNumber(v)
	return _c
}

// SetGhIssueID sets the "gh_issue_id" field.
func (_c *GithubIssueCreate) SetGhIssueID(v int64) *GithubIssueCreate {
	_c.mutation.SetGhIssueID(v)
	return _c
}

// SetRawData sets the "raw_data" field.
func (_c *GithubIssueCreate) SetRawData(v map[string]interface{}) *GithubIssueCreate {
	_c.mutation.SetRawData(v)
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *GithubIssueCreate) SetLastSyncedAt(v time.Time) *GithubIssueCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_c *GithubIssueCreate) SetNillableLastSyncedAt(v *time.Time) *GithubIssueCreate {
	if v != nil {
		_c.SetLastSyncedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GithubIssueCreate) SetID(v uuid.UUID) *GithubIssueCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *GithubIssueCreate) SetNillableID(v *uuid.UUID) *GithubIssueCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the Project entity.
func (_c *GithubIssueCreate) SetProject(v *Project) *GithubIssueCreate {
	return _c.SetProjectID(v.ID)
}

// SetTutorialContentID sets the "tutorial_content" edge to the TutorialContent entity by ID.
func (_c *GithubIssueCreate) SetTutorialContentID(id uuid.UUID) *GithubIssueCreate {
	_c.mutation.SetTutorialContentID(id)
	return _c
}

// SetNillableTutorialContentID sets the "tutorial_content" edge to the TutorialContent entity by ID if the given value is not nil.
func (_c *GithubIssueCreate) SetNillableTutorialContentID(id *uuid.UUID) *GithubIssueCreate {
	if id != nil {
		_c = _c.SetTutorialContentID(*id)
	}
	return _c
}

// SetTutorialContent sets the "tutorial_content" edge to the TutorialContent entity.
func (_c *GithubIssueCreate) SetTutorialContent(v *TutorialContent) *GithubIssueCreate {
	return _c.SetTutorialContentID(v.ID)
}

// Mutation returns the GithubIssueMutation object of the builder.
func (_c *GithubIssueCreate) Mutation() *GithubIssueMutation {
	return _c.mutation
}

// Save creates the GithubIssue in the database.
func (_c *GithubIssueCreate) Save(ctx context.Context) (*GithubIssue, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GithubIssueCreate) SaveX(ctx context.Context) *GithubIssue {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GithubIssueCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GithubIssueCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GithubIssueCreate) defaults() {
	if _, ok := _c.mutation.LastSyncedAt(); !ok {
		v := githubissue.DefaultLastSyncedAt()
		_c.mutation.SetLastSyncedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := githubissue.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GithubIssueCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "GithubIssue.project_id"`)}
	}
	if _, ok := _c.mutation.IssueNumber(); !ok {
		return &ValidationError{Name: "issue_number", err: errors.New(`ent: missing required field "GithubIssue.issue_number"`)}
	}
	if v, ok := _c.mutation.IssueNumber(); ok {
		if err := githubissue.IssueNumberValidator(v); err != nil {
			return &ValidationError{Name: "issue_number", err: fmt.Errorf(`ent: validator failed for field "GithubIssue.issue_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GhIssueID(); !ok {
		return &ValidationError{Name: "gh_issue_id", err: errors.New(`ent: missing required field "GithubIssue.gh_issue_id"`)}
	}
	if _, ok := _c.mutation.LastSyncedAt(); !ok {
		return &ValidationError{Name: "last_synced_at", err: errors.New(`ent: missing required field "GithubIssue.last_synced_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "GithubIssue.project"`)}
	}
	return nil
}

func (_c *GithubIssueCreate) sqlSave(ctx context.Context) (*GithubIssue, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GithubIssueCreate) createSpec() (*GithubIssue, *sqlgraph.CreateSpec) {
	var (
		_node = &GithubIssue{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(githubissue.Table, sqlgraph.NewFieldSpec(githubissue.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.IssueNumber(); ok {
		_spec.SetField(githubissue.FieldIssueNumber, field.TypeInt, value)
		_node.IssueNumber = value
	}
	if value, ok := _c.mutation.GhIssueID(); ok {
		_spec.SetField(githubissue.FieldGhIssueID, field.TypeInt64, value)
		_node.GhIssueID = value
	}
	if value, ok := _c.mutation.RawData(); ok {
		_spec.SetField(githubissue.FieldRawData, field.TypeJSON, value)
		_node.RawData = value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(githubissue.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   githubissue.ProjectTable,
			Columns: []string{githubissue.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TutorialContentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   githubissue.TutorialContentTable,
			Columns: []string{githubissue.TutorialContentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorialcontent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GithubIssueCreateBulk is the builder for creating many GithubIssue entities in bulk.
type GithubIssueCreateBulk struct {
	config
	err      error
	builders []*GithubIssueCreate
}

// Save creates the GithubIssue entities in the database.
func (_c *GithubIssueCreateBulk) Save(ctx context.Context) ([]*GithubIssue, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GithubIssue, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GithubIssueMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GithubIssueCreateBulk) SaveX(ctx context.Context) []*GithubIssue {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GithubIssueCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GithubIssueCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
