// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/concept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/project"
	"github.com/issuesight/issuesight/internal/platform/db/ent/projectconcept"
)

// ProjectConcept is the model entity for the ProjectConcept schema.
type ProjectConcept struct {
	config `json:"-"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// ConceptID holds the value of the "concept_id" field.
	ConceptID uuid.UUID `json:"concept_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectConceptQuery when eager-loading is set.
	Edges        ProjectConceptEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectConceptEdges holds the relations/edges for other nodes in the graph.
type ProjectConceptEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Concept holds the value of the concept edge.
	Concept *Concept `json:"concept,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectConceptEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// ConceptOrErr returns the Concept value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProjectConceptEdges) ConceptOrErr() (*Concept, error) {
	if e.Concept != nil {
		return e.Concept, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: concept.Label}
	}
	return nil, &NotLoadedError{edge: "concept"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProjectConcept) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projectconcept.FieldProjectID, projectconcept.FieldConceptID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProjectConcept fields.
func (_m *ProjectConcept) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projectconcept.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case projectconcept.FieldConceptID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field concept_id", values[i])
			} else if value != nil {
				_m.ConceptID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProjectConcept.
// This includes values selected through modifiers, order, etc.
func (_m *ProjectConcept) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the ProjectConcept entity.
func (_m *ProjectConcept) QueryProject() *ProjectQuery {
	return NewProjectConceptClient(_m.config).QueryProject(_m)
}

// QueryConcept queries the "concept" edge of the ProjectConcept entity.
func (_m *ProjectConcept) QueryConcept() *ConceptQuery {
	return NewProjectConceptClient(_m.config).QueryConcept(_m)
}

// Update returns a builder for updating this ProjectConcept.
// Note that you need to call ProjectConcept.Unwrap() before calling this method if this ProjectConcept
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProjectConcept) Update() *ProjectConceptUpdateOne {
	return NewProjectConceptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProjectConcept entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProjectConcept) Unwrap() *ProjectConcept {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProjectConcept is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProjectConcept) String() string {
	var builder strings.Builder
	builder.WriteString("ProjectConcept(")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("concept_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConceptID))
	builder.WriteByte(')')
	return builder.String()
}

// ProjectConcepts is a parsable slice of ProjectConcept.
type ProjectConcepts []*ProjectConcept
