// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/concept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/githubissue"
	"github.com/issuesight/issuesight/internal/platform/db/ent/predicate"
	"github.com/issuesight/issuesight/internal/platform/db/ent/project"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGhRepoID sets the "gh_repo_id" field.
func (_u *ProjectUpdate) SetGhRepoID(v int64) *ProjectUpdate {
	_u.mutation.ResetGhRepoID()
	_u.mutation.SetGhRepoID(v)
	return _u
}

// SetNillableGhRepoID sets the "gh_repo_id" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableGhRepoID(v *int64) *ProjectUpdate {
	if v != nil {
		_u.SetGhRepoID(*v)
	}
	return _u
}

// AddGhRepoID adds value to the "gh_repo_id" field.
func (_u *ProjectUpdate) AddGhRepoID(v int64) *ProjectUpdate {
	_u.mutation.AddGhRepoID(v)
	return _u
}

// SetOwnerHandle sets the "owner_handle" field.
func (_u *ProjectUpdate) SetOwnerHandle(v string) *ProjectUpdate {
	_u.mutation.SetOwnerHandle(v)
	return _u
}

// SetNillableOwnerHandle sets the "owner_handle" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableOwnerHandle(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetOwnerHandle(*v)
	}
	return _u
}

// SetRepoName sets the "repo_name" field.
func (_u *ProjectUpdate) SetRepoName(v string) *ProjectUpdate {
	_u.mutation.SetRepoName(v)
	return _u
}

// SetNillableRepoName sets the "repo_name" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableRepoName(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetRepoName(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *ProjectUpdate) SetFullName(v string) *ProjectUpdate {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableFullName(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *ProjectUpdate) SetLanguage(v string) *ProjectUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableLanguage(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *ProjectUpdate) ClearLanguage() *ProjectUpdate {
	_u.mutation.ClearLanguage()
	return _u
}

// AddIssueIDs adds the "issues" edge to the GithubIssue entity by IDs.
func (_u *ProjectUpdate) AddIssueIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddIssueIDs(ids...)
	return _u
}

// AddIssues adds the "issues" edges to the GithubIssue entity.
func (_u *ProjectUpdate) AddIssues(v ...*GithubIssue) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIssueIDs(ids...)
}

// AddConceptIDs adds the "concepts" edge to the Concept entity by IDs.
func (_u *ProjectUpdate) AddConceptIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddConceptIDs(ids...)
	return _u
}

// AddConcepts adds the "concepts" edges to the Concept entity.
func (_u *ProjectUpdate) AddConcepts(v ...*Concept) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConceptIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdate) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearIssues clears all "issues" edges to the GithubIssue entity.
func (_u *ProjectUpdate) ClearIssues() *ProjectUpdate {
	_u.mutation.ClearIssues()
	return _u
}

// RemoveIssueIDs removes the "issues" edge to GithubIssue entities by IDs.
func (_u *ProjectUpdate) RemoveIssueIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveIssueIDs(ids...)
	return _u
}

// RemoveIssues removes "issues" edges to GithubIssue entities.
func (_u *ProjectUpdate) RemoveIssues(v ...*GithubIssue) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIssueIDs(ids...)
}

// ClearConcepts clears all "concepts" edges to the Concept entity.
func (_u *ProjectUpdate) ClearConcepts() *ProjectUpdate {
	_u.mutation.ClearConcepts()
	return _u
}

// RemoveConceptIDs removes the "concepts" edge to Concept entities by IDs.
func (_u *ProjectUpdate) RemoveConceptIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveConceptIDs(ids...)
	return _u
}

// RemoveConcepts removes "concepts" edges to Concept entities.
func (_u *ProjectUpdate) RemoveConcepts(v ...*Concept) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConceptIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdate) check() error {
	if v, ok := _u.mutation.OwnerHandle(); ok {
		if err := project.OwnerHandleValidator(v); err != nil {
			return &ValidationError{Name: "owner_handle", err: fmt.Errorf(`ent: validator failed for field "Project.owner_handle": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoName(); ok {
		if err := project.RepoNameValidator(v); err != nil {
			return &ValidationError{Name: "repo_name", err: fmt.Errorf(`ent: validator failed for field "Project.repo_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FullName(); ok {
		if err := project.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "Project.full_name": %w`, err)}
		}
	}
	return nil
}

func (_u *ProjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GhRepoID(); ok {
		_spec.SetField(project.FieldGhRepoID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGhRepoID(); ok {
		_spec.AddField(project.FieldGhRepoID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerHandle(); ok {
		_spec.SetField(project.FieldOwnerHandle, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoName(); ok {
		_spec.SetField(project.FieldRepoName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(project.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(project.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(project.FieldLanguage, field.TypeString)
	}
	if _u.mutation.IssuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.IssuesTable,
			Columns: []string{project.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubissue.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIssuesIDs(); len(nodes) > 0 && !_u.mutation.IssuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.IssuesTable,
			Columns: []string{project.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubissue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IssuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.IssuesTable,
			Columns: []string{project.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubissue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.ConceptsTable,
			Columns: project.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConceptsIDs(); len(nodes) > 0 && !_u.mutation.ConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.ConceptsTable,
			Columns: project.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConceptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.ConceptsTable,
			Columns: project.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetGhRepoID sets the "gh_repo_id" field.
func (_u *ProjectUpdateOne) SetGhRepoID(v int64) *ProjectUpdateOne {
	_u.mutation.ResetGhRepoID()
	_u.mutation.SetGhRepoID(v)
	return _u
}

// SetNillableGhRepoID sets the "gh_repo_id" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableGhRepoID(v *int64) *ProjectUpdateOne {
	if v != nil {
		_u.SetGhRepoID(*v)
	}
	return _u
}

// AddGhRepoID adds value to the "gh_repo_id" field.
func (_u *ProjectUpdateOne) AddGhRepoID(v int64) *ProjectUpdateOne {
	_u.mutation.AddGhRepoID(v)
	return _u
}

// SetOwnerHandle sets the "owner_handle" field.
func (_u *ProjectUpdateOne) SetOwnerHandle(v string) *ProjectUpdateOne {
	_u.mutation.SetOwnerHandle(v)
	return _u
}

// SetNillableOwnerHandle sets the "owner_handle" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableOwnerHandle(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetOwnerHandle(*v)
	}
	return _u
}

// SetRepoName sets the "repo_name" field.
func (_u *ProjectUpdateOne) SetRepoName(v string) *ProjectUpdateOne {
	_u.mutation.SetRepoName(v)
	return _u
}

// SetNillableRepoName sets the "repo_name" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableRepoName(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetRepoName(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *ProjectUpdateOne) SetFullName(v string) *ProjectUpdateOne {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableFullName(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *ProjectUpdateOne) SetLanguage(v string) *ProjectUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableLanguage(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// ClearLanguage clears the value of the "language" field.
func (_u *ProjectUpdateOne) ClearLanguage() *ProjectUpdateOne {
	_u.mutation.ClearLanguage()
	return _u
}

// AddIssueIDs adds the "issues" edge to the GithubIssue entity by IDs.
func (_u *ProjectUpdateOne) AddIssueIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddIssueIDs(ids...)
	return _u
}

// AddIssues adds the "issues" edges to the GithubIssue entity.
func (_u *ProjectUpdateOne) AddIssues(v ...*GithubIssue) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIssueIDs(ids...)
}

// AddConceptIDs adds the "concepts" edge to the Concept entity by IDs.
func (_u *ProjectUpdateOne) AddConceptIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddConceptIDs(ids...)
	return _u
}

// AddConcepts adds the "concepts" edges to the Concept entity.
func (_u *ProjectUpdateOne) AddConcepts(v ...*Concept) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConceptIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdateOne) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearIssues clears all "issues" edges to the GithubIssue entity.
func (_u *ProjectUpdateOne) ClearIssues() *ProjectUpdateOne {
	_u.mutation.ClearIssues()
	return _u
}

// RemoveIssueIDs removes the "issues" edge to GithubIssue entities by IDs.
func (_u *ProjectUpdateOne) RemoveIssueIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveIssueIDs(ids...)
	return _u
}

// RemoveIssues removes "issues" edges to GithubIssue entities.
func (_u *ProjectUpdateOne) RemoveIssues(v ...*GithubIssue) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIssueIDs(ids...)
}

// ClearConcepts clears all "concepts" edges to the Concept entity.
func (_u *ProjectUpdateOne) ClearConcepts() *ProjectUpdateOne {
	_u.mutation.ClearConcepts()
	return _u
}

// RemoveConceptIDs removes the "concepts" edge to Concept entities by IDs.
func (_u *ProjectUpdateOne) RemoveConceptIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveConceptIDs(ids...)
	return _u
}

// RemoveConcepts removes "concepts" edges to Concept entities.
func (_u *ProjectUpdateOne) RemoveConcepts(v ...*Concept) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConceptIDs(ids...)
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdateOne) Where(ps ...predicate.Project) *ProjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Project entity.
func (_u *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdateOne) check() error {
	if v, ok := _u.mutation.OwnerHandle(); ok {
		if err := project.OwnerHandleValidator(v); err != nil {
			return &ValidationError{Name: "owner_handle", err: fmt.Errorf(`ent: validator failed for field "Project.owner_handle": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RepoName(); ok {
		if err := project.RepoNameValidator(v); err != nil {
			return &ValidationError{Name: "repo_name", err: fmt.Errorf(`ent: validator failed for field "Project.repo_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FullName(); ok {
		if err := project.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "Project.full_name": %w`, err)}
		}
	}
	return nil
}

func (_u *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GhRepoID(); ok {
		_spec.SetField(project.FieldGhRepoID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGhRepoID(); ok {
		_spec.AddField(project.FieldGhRepoID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OwnerHandle(); ok {
		_spec.SetField(project.FieldOwnerHandle, field.TypeString, value)
	}
	if value, ok := _u.mutation.RepoName(); ok {
		_spec.SetField(project.FieldRepoName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(project.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(project.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.LanguageCleared() {
		_spec.ClearField(project.FieldLanguage, field.TypeString)
	}
	if _u.mutation.IssuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.IssuesTable,
			Columns: []string{project.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubissue.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIssuesIDs(); len(nodes) > 0 && !_u.mutation.IssuesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.IssuesTable,
			Columns: []string{project.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubissue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IssuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.IssuesTable,
			Columns: []string{project.IssuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubissue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.ConceptsTable,
			Columns: project.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConceptsIDs(); len(nodes) > 0 && !_u.mutation.ConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.ConceptsTable,
			Columns: project.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConceptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   project.ConceptsTable,
			Columns: project.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Project{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
