// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/concept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/conceptrelationship"
	"github.com/issuesight/issuesight/internal/platform/db/ent/githubissue"
	"github.com/issuesight/issuesight/internal/platform/db/ent/project"
	"github.com/issuesight/issuesight/internal/platform/db/ent/schema"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorial"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialcontent"
	"github.com/issuesight/issuesight/internal/platform/db/ent/user"
	"github.com/issuesight/issuesight/internal/platform/db/ent/useridentity"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	conceptFields := schema.Concept{}.Fields()
	_ = conceptFields
	// conceptDescSlug is the schema descriptor for slug field.
	conceptDescSlug := conceptFields[1].Descriptor()
	// concept.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	concept.SlugValidator = conceptDescSlug.Validators[0].(func(string) error)
	// conceptDescName is the schema descriptor for name field.
	conceptDescName := conceptFields[2].Descriptor()
	// concept.NameValidator is a validator for the "name" field. It is called by the builders before save.
	concept.NameValidator = conceptDescName.Validators[0].(func(string) error)
	// conceptDescID is the schema descriptor for id field.
	conceptDescID := conceptFields[0].Descriptor()
	// concept.DefaultID holds the default value on creation for the id field.
	concept.DefaultID = conceptDescID.Default.(func() uuid.UUID)
	conceptrelationshipFields := schema.ConceptRelationship{}.Fields()
	_ = conceptrelationshipFields
	// conceptrelationshipDescRelType is the schema descriptor for rel_type field.
	conceptrelationshipDescRelType := conceptrelationshipFields[3].Descriptor()
	// conceptrelationship.DefaultRelType holds the default value on creation for the rel_type field.
	conceptrelationship.DefaultRelType = conceptrelationshipDescRelType.Default.(string)
	// conceptrelationshipDescID is the schema descriptor for id field.
	conceptrelationshipDescID := conceptrelationshipFields[0].Descriptor()
	// conceptrelationship.DefaultID holds the default value on creation for the id field.
	conceptrelationship.DefaultID = conceptrelationshipDescID.Default.(func() uuid.UUID)
	githubissueFields := schema.GithubIssue{}.Fields()
	_ = githubissueFields
	// githubissueDescIssueNumber is the schema descriptor for issue_number field.
	githubissueDescIssueNumber := githubissueFields[2].Descriptor()
	// githubissue.IssueNumberValidator is a validator for the "issue_number" field. It is called by the builders before save.
	githubissue.IssueNumberValidator = githubissueDescIssueNumber.Validators[0].(func(int) error)
	// githubissueDescLastSyncedAt is the schema descriptor for last_synced_at field.
	githubissueDescLastSyncedAt := githubissueFields[5].Descriptor()
	// githubissue.DefaultLastSyncedAt holds the default value on creation for the last_synced_at field.
	githubissue.DefaultLastSyncedAt = githubissueDescLastSyncedAt.Default.(func() time.Time)
	// githubissueDescID is the schema descriptor for id field.
	githubissueDescID := githubissueFields[0].Descriptor()
	// githubissue.DefaultID holds the default value on creation for the id field.
	githubissue.DefaultID = githubissueDescID.Default.(func() uuid.UUID)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescOwnerHandle is the schema descriptor for owner_handle field.
	projectDescOwnerHandle := projectFields[2].Descriptor()
	// project.OwnerHandleValidator is a validator for the "owner_handle" field. It is called by the builders before save.
	project.OwnerHandleValidator = projectDescOwnerHandle.Validators[0].(func(string) error)
	// projectDescRepoName is the schema descriptor for repo_name field.
	projectDescRepoName := projectFields[3].Descriptor()
	// project.RepoNameValidator is a validator for the "repo_name" field. It is called by the builders before save.
	project.RepoNameValidator = projectDescRepoName.Validators[0].(func(string) error)
	// projectDescFullName is the schema descriptor for full_name field.
	projectDescFullName := projectFields[4].Descriptor()
	// project.FullNameValidator is a validator for the "full_name" field. It is called by the builders before save.
	project.FullNameValidator = projectDescFullName.Validators[0].(func(string) error)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[6].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(func() uuid.UUID)
	tutorialFields := schema.Tutorial{}.Fields()
	_ = tutorialFields
	// tutorialDescIsOriginalRequester is the schema descriptor for is_original_requester field.
	tutorialDescIsOriginalRequester := tutorialFields[3].Descriptor()
	// tutorial.DefaultIsOriginalRequester holds the default value on creation for the is_original_requester field.
	tutorial.DefaultIsOriginalRequester = tutorialDescIsOriginalRequester.Default.(bool)
	// tutorialDescCreatedAt is the schema descriptor for created_at field.
	tutorialDescCreatedAt := tutorialFields[4].Descriptor()
	// tutorial.DefaultCreatedAt holds the default value on creation for the created_at field.
	tutorial.DefaultCreatedAt = tutorialDescCreatedAt.Default.(func() time.Time)
	// tutorialDescID is the schema descriptor for id field.
	tutorialDescID := tutorialFields[0].Descriptor()
	// tutorial.DefaultID holds the default value on creation for the id field.
	tutorial.DefaultID = tutorialDescID.Default.(func() uuid.UUID)
	tutorialcontentFields := schema.TutorialContent{}.Fields()
	_ = tutorialcontentFields
	// tutorialcontentDescTitle is the schema descriptor for title field.
	tutorialcontentDescTitle := tutorialcontentFields[2].Descriptor()
	// tutorialcontent.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	tutorialcontent.TitleValidator = tutorialcontentDescTitle.Validators[0].(func(string) error)
	// tutorialcontentDescCreatedAt is the schema descriptor for created_at field.
	tutorialcontentDescCreatedAt := tutorialcontentFields[5].Descriptor()
	// tutorialcontent.DefaultCreatedAt holds the default value on creation for the created_at field.
	tutorialcontent.DefaultCreatedAt = tutorialcontentDescCreatedAt.Default.(func() time.Time)
	// tutorialcontentDescUpdatedAt is the schema descriptor for updated_at field.
	tutorialcontentDescUpdatedAt := tutorialcontentFields[6].Descriptor()
	// tutorialcontent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tutorialcontent.DefaultUpdatedAt = tutorialcontentDescUpdatedAt.Default.(func() time.Time)
	// tutorialcontent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tutorialcontent.UpdateDefaultUpdatedAt = tutorialcontentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tutorialcontentDescID is the schema descriptor for id field.
	tutorialcontentDescID := tutorialcontentFields[0].Descriptor()
	// tutorialcontent.DefaultID holds the default value on creation for the id field.
	tutorialcontent.DefaultID = tutorialcontentDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	useridentityFields := schema.UserIdentity{}.Fields()
	_ = useridentityFields
	// useridentityDescProvider is the schema descriptor for provider field.
	useridentityDescProvider := useridentityFields[2].Descriptor()
	// useridentity.ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	useridentity.ProviderValidator = useridentityDescProvider.Validators[0].(func(string) error)
	// useridentityDescProviderID is the schema descriptor for provider_id field.
	useridentityDescProviderID := useridentityFields[3].Descriptor()
	// useridentity.ProviderIDValidator is a validator for the "provider_id" field. It is called by the builders before save.
	useridentity.ProviderIDValidator = useridentityDescProviderID.Validators[0].(func(string) error)
	// useridentityDescID is the schema descriptor for id field.
	useridentityDescID := useridentityFields[0].Descriptor()
	// useridentity.DefaultID holds the default value on creation for the id field.
	useridentity.DefaultID = useridentityDescID.Default.(func() uuid.UUID)
}
