// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/issuesight/issuesight/internal/platform/db/ent/predicate"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorial"
)

// TutorialDelete is the builder for deleting a Tutorial entity.
type TutorialDelete struct {
	config
	hooks    []Hook
	mutation *TutorialMutation
}

// Where appends a list predicates to the TutorialDelete builder.
func (_d *TutorialDelete) Where(ps ...predicate.Tutorial) *TutorialDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TutorialDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TutorialDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TutorialDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tutorial.Table, sqlgraph.NewFieldSpec(tutorial.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TutorialDeleteOne is the builder for deleting a single Tutorial entity.
type TutorialDeleteOne struct {
	_d *TutorialDelete
}

// Where appends a list predicates to the TutorialDelete builder.
func (_d *TutorialDeleteOne) Where(ps ...predicate.Tutorial) *TutorialDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TutorialDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tutorial.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TutorialDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
