// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/githubissue"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialcontent"
)

// TutorialContent is the model entity for the TutorialContent schema.
type TutorialContent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// One tutorial content per issue
	IssueID uuid.UUID `json:"issue_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// The AI-generated tutorial content
	MarkdownBody string `json:"markdown_body,omitempty"`
	// Status holds the value of the "status" field.
	Status tutorialcontent.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TutorialContentQuery when eager-loading is set.
	Edges        TutorialContentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TutorialContentEdges holds the relations/edges for other nodes in the graph.
type TutorialContentEdges struct {
	// Issue holds the value of the issue edge.
	Issue *GithubIssue `json:"issue,omitempty"`
	// Tutorials holds the value of the tutorials edge.
	Tutorials []*Tutorial `json:"tutorials,omitempty"`
	// Concepts holds the value of the concepts edge.
	Concepts []*Concept `json:"concepts,omitempty"`
	// TutorialConcepts holds the value of the tutorial_concepts edge.
	TutorialConcepts []*TutorialConcept `json:"tutorial_concepts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// IssueOrErr returns the Issue value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TutorialContentEdges) IssueOrErr() (*GithubIssue, error) {
	if e.Issue != nil {
		return e.Issue, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: githubissue.Label}
	}
	return nil, &NotLoadedError{edge: "issue"}
}

// TutorialsOrErr returns the Tutorials value or an error if the edge
// was not loaded in eager-loading.
func (e TutorialContentEdges) TutorialsOrErr() ([]*Tutorial, error) {
	if e.loadedTypes[1] {
		return e.Tutorials, nil
	}
	return nil, &NotLoadedError{edge: "tutorials"}
}

// ConceptsOrErr returns the Concepts value or an error if the edge
// was not loaded in eager-loading.
func (e TutorialContentEdges) ConceptsOrErr() ([]*Concept, error) {
	if e.loadedTypes[2] {
		return e.Concepts, nil
	}
	return nil, &NotLoadedError{edge: "concepts"}
}

// TutorialConceptsOrErr returns the TutorialConcepts value or an error if the edge
// was not loaded in eager-loading.
func (e TutorialContentEdges) TutorialConceptsOrErr() ([]*TutorialConcept, error) {
	if e.loadedTypes[3] {
		return e.TutorialConcepts, nil
	}
	return nil, &NotLoadedError{edge: "tutorial_concepts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TutorialContent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tutorialcontent.FieldTitle, tutorialcontent.FieldMarkdownBody, tutorialcontent.FieldStatus:
			values[i] = new(sql.NullString)
		case tutorialcontent.FieldCreatedAt, tutorialcontent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case tutorialcontent.FieldID, tutorialcontent.FieldIssueID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TutorialContent fields.
func (_m *TutorialContent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tutorialcontent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case tutorialcontent.FieldIssueID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field issue_id", values[i])
			} else if value != nil {
				_m.IssueID = *value
			}
		case tutorialcontent.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case tutorialcontent.FieldMarkdownBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field markdown_body", values[i])
			} else if value.Valid {
				_m.MarkdownBody = value.String
			}
		case tutorialcontent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = tutorialcontent.Status(value.String)
			}
		case tutorialcontent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tutorialcontent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TutorialContent.
// This includes values selected through modifiers, order, etc.
func (_m *TutorialContent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryIssue queries the "issue" edge of the TutorialContent entity.
func (_m *TutorialContent) QueryIssue() *GithubIssueQuery {
	return NewTutorialContentClient(_m.config).QueryIssue(_m)
}

// QueryTutorials queries the "tutorials" edge of the TutorialContent entity.
func (_m *TutorialContent) QueryTutorials() *TutorialQuery {
	return NewTutorialContentClient(_m.config).QueryTutorials(_m)
}

// QueryConcepts queries the "concepts" edge of the TutorialContent entity.
func (_m *TutorialContent) QueryConcepts() *ConceptQuery {
	return NewTutorialContentClient(_m.config).QueryConcepts(_m)
}

// QueryTutorialConcepts queries the "tutorial_concepts" edge of the TutorialContent entity.
func (_m *TutorialContent) QueryTutorialConcepts() *TutorialConceptQuery {
	return NewTutorialContentClient(_m.config).QueryTutorialConcepts(_m)
}

// Update returns a builder for updating this TutorialContent.
// Note that you need to call TutorialContent.Unwrap() before calling this method if this TutorialContent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TutorialContent) Update() *TutorialContentUpdateOne {
	return NewTutorialContentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TutorialContent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TutorialContent) Unwrap() *TutorialContent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TutorialContent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TutorialContent) String() string {
	var builder strings.Builder
	builder.WriteString("TutorialContent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("issue_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.IssueID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("markdown_body=")
	builder.WriteString(_m.MarkdownBody)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TutorialContents is a parsable slice of TutorialContent.
type TutorialContents []*TutorialContent
