// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/concept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/predicate"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialconcept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialcontent"
)

// TutorialConceptQuery is the builder for querying TutorialConcept entities.
type TutorialConceptQuery struct {
	config
	ctx         *QueryContext
	order       []tutorialconcept.OrderOption
	inters      []Interceptor
	predicates  []predicate.TutorialConcept
	withContent *TutorialContentQuery
	withConcept *ConceptQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TutorialConceptQuery builder.
func (_q *TutorialConceptQuery) Where(ps ...predicate.TutorialConcept) *TutorialConceptQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *TutorialConceptQuery) Limit(limit int) *TutorialConceptQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *TutorialConceptQuery) Offset(offset int) *TutorialConceptQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *TutorialConceptQuery) Unique(unique bool) *TutorialConceptQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *TutorialConceptQuery) Order(o ...tutorialconcept.OrderOption) *TutorialConceptQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryContent chains the current query on the "content" edge.
func (_q *TutorialConceptQuery) QueryContent() *TutorialContentQuery {
	query := (&TutorialContentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tutorialconcept.Table, tutorialconcept.ContentColumn, selector),
			sqlgraph.To(tutorialcontent.Table, tutorialcontent.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, tutorialconcept.ContentTable, tutorialconcept.ContentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryConcept chains the current query on the "concept" edge.
func (_q *TutorialConceptQuery) QueryConcept() *ConceptQuery {
	query := (&ConceptClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tutorialconcept.Table, tutorialconcept.ConceptColumn, selector),
			sqlgraph.To(concept.Table, concept.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, tutorialconcept.ConceptTable, tutorialconcept.ConceptColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TutorialConcept entity from the query.
// Returns a *NotFoundError when no TutorialConcept was found.
func (_q *TutorialConceptQuery) First(ctx context.Context) (*TutorialConcept, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tutorialconcept.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *TutorialConceptQuery) FirstX(ctx context.Context) *TutorialConcept {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single TutorialConcept entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TutorialConcept entity is found.
// Returns a *NotFoundError when no TutorialConcept entities are found.
func (_q *TutorialConceptQuery) Only(ctx context.Context) (*TutorialConcept, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tutorialconcept.Label}
	default:
		return nil, &NotSingularError{tutorialconcept.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *TutorialConceptQuery) OnlyX(ctx context.Context) *TutorialConcept {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of TutorialConcepts.
func (_q *TutorialConceptQuery) All(ctx context.Context) ([]*TutorialConcept, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TutorialConcept, *TutorialConceptQuery]()
	return withInterceptors[[]*TutorialConcept](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *TutorialConceptQuery) AllX(ctx context.Context) []*TutorialConcept {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (_q *TutorialConceptQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*TutorialConceptQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *TutorialConceptQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *TutorialConceptQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *TutorialConceptQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TutorialConceptQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *TutorialConceptQuery) Clone() *TutorialConceptQuery {
	if _q == nil {
		return nil
	}
	return &TutorialConceptQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]tutorialconcept.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.TutorialConcept{}, _q.predicates...),
		withContent: _q.withContent.Clone(),
		withConcept: _q.withConcept.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithContent tells the query-builder to eager-load the nodes that are connected to
// the "content" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TutorialConceptQuery) WithContent(opts ...func(*TutorialContentQuery)) *TutorialConceptQuery {
	query := (&TutorialContentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withContent = query
	return _q
}

// WithConcept tells the query-builder to eager-load the nodes that are connected to
// the "concept" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *TutorialConceptQuery) WithConcept(opts ...func(*ConceptQuery)) *TutorialConceptQuery {
	query := (&ConceptClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withConcept = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ContentID uuid.UUID `json:"content_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TutorialConcept.Query().
//		GroupBy(tutorialconcept.FieldContentID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *TutorialConceptQuery) GroupBy(field string, fields ...string) *TutorialConceptGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TutorialConceptGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = tutorialconcept.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ContentID uuid.UUID `json:"content_id,omitempty"`
//	}
//
//	client.TutorialConcept.Query().
//		Select(tutorialconcept.FieldContentID).
//		Scan(ctx, &v)
func (_q *TutorialConceptQuery) Select(fields ...string) *TutorialConceptSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &TutorialConceptSelect{TutorialConceptQuery: _q}
	sbuild.label = tutorialconcept.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TutorialConceptSelect configured with the given aggregations.
func (_q *TutorialConceptQuery) Aggregate(fns ...AggregateFunc) *TutorialConceptSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *TutorialConceptQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !tutorialconcept.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *TutorialConceptQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TutorialConcept, error) {
	var (
		nodes       = []*TutorialConcept{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withContent != nil,
			_q.withConcept != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TutorialConcept).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TutorialConcept{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withContent; query != nil {
		if err := _q.loadContent(ctx, query, nodes, nil,
			func(n *TutorialConcept, e *TutorialContent) { n.Edges.Content = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withConcept; query != nil {
		if err := _q.loadConcept(ctx, query, nodes, nil,
			func(n *TutorialConcept, e *Concept) { n.Edges.Concept = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *TutorialConceptQuery) loadContent(ctx context.Context, query *TutorialContentQuery, nodes []*TutorialConcept, init func(*TutorialConcept), assign func(*TutorialConcept, *TutorialContent)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TutorialConcept)
	for i := range nodes {
		fk := nodes[i].ContentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tutorialcontent.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "content_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *TutorialConceptQuery) loadConcept(ctx context.Context, query *ConceptQuery, nodes []*TutorialConcept, init func(*TutorialConcept), assign func(*TutorialConcept, *Concept)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*TutorialConcept)
	for i := range nodes {
		fk := nodes[i].ConceptID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(concept.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "concept_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *TutorialConceptQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *TutorialConceptQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tutorialconcept.Table, tutorialconcept.Columns, nil)
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if _q.withContent != nil {
			_spec.Node.AddColumnOnce(tutorialconcept.FieldContentID)
		}
		if _q.withConcept != nil {
			_spec.Node.AddColumnOnce(tutorialconcept.FieldConceptID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *TutorialConceptQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(tutorialconcept.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = tutorialconcept.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TutorialConceptGroupBy is the group-by builder for TutorialConcept entities.
type TutorialConceptGroupBy struct {
	selector
	build *TutorialConceptQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *TutorialConceptGroupBy) Aggregate(fns ...AggregateFunc) *TutorialConceptGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *TutorialConceptGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TutorialConceptQuery, *TutorialConceptGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *TutorialConceptGroupBy) sqlScan(ctx context.Context, root *TutorialConceptQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TutorialConceptSelect is the builder for selecting fields of TutorialConcept entities.
type TutorialConceptSelect struct {
	*TutorialConceptQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *TutorialConceptSelect) Aggregate(fns ...AggregateFunc) *TutorialConceptSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *TutorialConceptSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TutorialConceptQuery, *TutorialConceptSelect](ctx, _s.TutorialConceptQuery, _s, _s.inters, v)
}

func (_s *TutorialConceptSelect) sqlScan(ctx context.Context, root *TutorialConceptQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
