// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/concept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/githubissue"
	"github.com/issuesight/issuesight/internal/platform/db/ent/predicate"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorial"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialcontent"
)

// TutorialContentUpdate is the builder for updating TutorialContent entities.
type TutorialContentUpdate struct {
	config
	hooks    []Hook
	mutation *TutorialContentMutation
}

// Where appends a list predicates to the TutorialContentUpdate builder.
func (_u *TutorialContentUpdate) Where(ps ...predicate.TutorialContent) *TutorialContentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIssueID sets the "issue_id" field.
func (_u *TutorialContentUpdate) SetIssueID(v uuid.UUID) *TutorialContentUpdate {
	_u.mutation.SetIssueID(v)
	return _u
}

// SetNillableIssueID sets the "issue_id" field if the given value is not nil.
func (_u *TutorialContentUpdate) SetNillableIssueID(v *uuid.UUID) *TutorialContentUpdate {
	if v != nil {
		_u.SetIssueID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *TutorialContentUpdate) SetTitle(v string) *TutorialContentUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TutorialContentUpdate) SetNillableTitle(v *string) *TutorialContentUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetMarkdownBody sets the "markdown_body" field.
func (_u *TutorialContentUpdate) SetMarkdownBody(v string) *TutorialContentUpdate {
	_u.mutation.SetMarkdownBody(v)
	return _u
}

// SetNillableMarkdownBody sets the "markdown_body" field if the given value is not nil.
func (_u *TutorialContentUpdate) SetNillableMarkdownBody(v *string) *TutorialContentUpdate {
	if v != nil {
		_u.SetMarkdownBody(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TutorialContentUpdate) SetStatus(v tutorialcontent.Status) *TutorialContentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TutorialContentUpdate) SetNillableStatus(v *tutorialcontent.Status) *TutorialContentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TutorialContentUpdate) SetUpdatedAt(v time.Time) *TutorialContentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIssue sets the "issue" edge to the GithubIssue entity.
func (_u *TutorialContentUpdate) SetIssue(v *GithubIssue) *TutorialContentUpdate {
	return _u.SetIssueID(v.ID)
}

// AddTutorialIDs adds the "tutorials" edge to the Tutorial entity by IDs.
func (_u *TutorialContentUpdate) AddTutorialIDs(ids ...uuid.UUID) *TutorialContentUpdate {
	_u.mutation.AddTutorialIDs(ids...)
	return _u
}

// AddTutorials adds the "tutorials" edges to the Tutorial entity.
func (_u *TutorialContentUpdate) AddTutorials(v ...*Tutorial) *TutorialContentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTutorialIDs(ids...)
}

// AddConceptIDs adds the "concepts" edge to the Concept entity by IDs.
func (_u *TutorialContentUpdate) AddConceptIDs(ids ...uuid.UUID) *TutorialContentUpdate {
	_u.mutation.AddConceptIDs(ids...)
	return _u
}

// AddConcepts adds the "concepts" edges to the Concept entity.
func (_u *TutorialContentUpdate) AddConcepts(v ...*Concept) *TutorialContentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConceptIDs(ids...)
}

// Mutation returns the TutorialContentMutation object of the builder.
func (_u *TutorialContentUpdate) Mutation() *TutorialContentMutation {
	return _u.mutation
}

// ClearIssue clears the "issue" edge to the GithubIssue entity.
func (_u *TutorialContentUpdate) ClearIssue() *TutorialContentUpdate {
	_u.mutation.ClearIssue()
	return _u
}

// ClearTutorials clears all "tutorials" edges to the Tutorial entity.
func (_u *TutorialContentUpdate) ClearTutorials() *TutorialContentUpdate {
	_u.mutation.ClearTutorials()
	return _u
}

// RemoveTutorialIDs removes the "tutorials" edge to Tutorial entities by IDs.
func (_u *TutorialContentUpdate) RemoveTutorialIDs(ids ...uuid.UUID) *TutorialContentUpdate {
	_u.mutation.RemoveTutorialIDs(ids...)
	return _u
}

// RemoveTutorials removes "tutorials" edges to Tutorial entities.
func (_u *TutorialContentUpdate) RemoveTutorials(v ...*Tutorial) *TutorialContentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTutorialIDs(ids...)
}

// ClearConcepts clears all "concepts" edges to the Concept entity.
func (_u *TutorialContentUpdate) ClearConcepts() *TutorialContentUpdate {
	_u.mutation.ClearConcepts()
	return _u
}

// RemoveConceptIDs removes the "concepts" edge to Concept entities by IDs.
func (_u *TutorialContentUpdate) RemoveConceptIDs(ids ...uuid.UUID) *TutorialContentUpdate {
	_u.mutation.RemoveConceptIDs(ids...)
	return _u
}

// RemoveConcepts removes "concepts" edges to Concept entities.
func (_u *TutorialContentUpdate) RemoveConcepts(v ...*Concept) *TutorialContentUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConceptIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TutorialContentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TutorialContentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TutorialContentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TutorialContentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TutorialContentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tutorialcontent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TutorialContentUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := tutorialcontent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "TutorialContent.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tutorialcontent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TutorialContent.status": %w`, err)}
		}
	}
	if _u.mutation.IssueCleared() && len(_u.mutation.IssueIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TutorialContent.issue"`)
	}
	return nil
}

func (_u *TutorialContentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tutorialcontent.Table, tutorialcontent.Columns, sqlgraph.NewFieldSpec(tutorialcontent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(tutorialcontent.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.MarkdownBody(); ok {
		_spec.SetField(tutorialcontent.FieldMarkdownBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tutorialcontent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tutorialcontent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.IssueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tutorialcontent.IssueTable,
			Columns: []string{tutorialcontent.IssueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubissue.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IssueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tutorialcontent.IssueTable,
			Columns: []string{tutorialcontent.IssueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubissue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TutorialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tutorialcontent.TutorialsTable,
			Columns: []string{tutorialcontent.TutorialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorial.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTutorialsIDs(); len(nodes) > 0 && !_u.mutation.TutorialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tutorialcontent.TutorialsTable,
			Columns: []string{tutorialcontent.TutorialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorial.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TutorialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tutorialcontent.TutorialsTable,
			Columns: []string{tutorialcontent.TutorialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorial.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tutorialcontent.ConceptsTable,
			Columns: tutorialcontent.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConceptsIDs(); len(nodes) > 0 && !_u.mutation.ConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tutorialcontent.ConceptsTable,
			Columns: tutorialcontent.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConceptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tutorialcontent.ConceptsTable,
			Columns: tutorialcontent.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tutorialcontent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TutorialContentUpdateOne is the builder for updating a single TutorialContent entity.
type TutorialContentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TutorialContentMutation
}

// SetIssueID sets the "issue_id" field.
func (_u *TutorialContentUpdateOne) SetIssueID(v uuid.UUID) *TutorialContentUpdateOne {
	_u.mutation.SetIssueID(v)
	return _u
}

// SetNillableIssueID sets the "issue_id" field if the given value is not nil.
func (_u *TutorialContentUpdateOne) SetNillableIssueID(v *uuid.UUID) *TutorialContentUpdateOne {
	if v != nil {
		_u.SetIssueID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *TutorialContentUpdateOne) SetTitle(v string) *TutorialContentUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TutorialContentUpdateOne) SetNillableTitle(v *string) *TutorialContentUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetMarkdownBody sets the "markdown_body" field.
func (_u *TutorialContentUpdateOne) SetMarkdownBody(v string) *TutorialContentUpdateOne {
	_u.mutation.SetMarkdownBody(v)
	return _u
}

// SetNillableMarkdownBody sets the "markdown_body" field if the given value is not nil.
func (_u *TutorialContentUpdateOne) SetNillableMarkdownBody(v *string) *TutorialContentUpdateOne {
	if v != nil {
		_u.SetMarkdownBody(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TutorialContentUpdateOne) SetStatus(v tutorialcontent.Status) *TutorialContentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TutorialContentUpdateOne) SetNillableStatus(v *tutorialcontent.Status) *TutorialContentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TutorialContentUpdateOne) SetUpdatedAt(v time.Time) *TutorialContentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetIssue sets the "issue" edge to the GithubIssue entity.
func (_u *TutorialContentUpdateOne) SetIssue(v *GithubIssue) *TutorialContentUpdateOne {
	return _u.SetIssueID(v.ID)
}

// AddTutorialIDs adds the "tutorials" edge to the Tutorial entity by IDs.
func (_u *TutorialContentUpdateOne) AddTutorialIDs(ids ...uuid.UUID) *TutorialContentUpdateOne {
	_u.mutation.AddTutorialIDs(ids...)
	return _u
}

// AddTutorials adds the "tutorials" edges to the Tutorial entity.
func (_u *TutorialContentUpdateOne) AddTutorials(v ...*Tutorial) *TutorialContentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTutorialIDs(ids...)
}

// AddConceptIDs adds the "concepts" edge to the Concept entity by IDs.
func (_u *TutorialContentUpdateOne) AddConceptIDs(ids ...uuid.UUID) *TutorialContentUpdateOne {
	_u.mutation.AddConceptIDs(ids...)
	return _u
}

// AddConcepts adds the "concepts" edges to the Concept entity.
func (_u *TutorialContentUpdateOne) AddConcepts(v ...*Concept) *TutorialContentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConceptIDs(ids...)
}

// Mutation returns the TutorialContentMutation object of the builder.
func (_u *TutorialContentUpdateOne) Mutation() *TutorialContentMutation {
	return _u.mutation
}

// ClearIssue clears the "issue" edge to the GithubIssue entity.
func (_u *TutorialContentUpdateOne) ClearIssue() *TutorialContentUpdateOne {
	_u.mutation.ClearIssue()
	return _u
}

// ClearTutorials clears all "tutorials" edges to the Tutorial entity.
func (_u *TutorialContentUpdateOne) ClearTutorials() *TutorialContentUpdateOne {
	_u.mutation.ClearTutorials()
	return _u
}

// RemoveTutorialIDs removes the "tutorials" edge to Tutorial entities by IDs.
func (_u *TutorialContentUpdateOne) RemoveTutorialIDs(ids ...uuid.UUID) *TutorialContentUpdateOne {
	_u.mutation.RemoveTutorialIDs(ids...)
	return _u
}

// RemoveTutorials removes "tutorials" edges to Tutorial entities.
func (_u *TutorialContentUpdateOne) RemoveTutorials(v ...*Tutorial) *TutorialContentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTutorialIDs(ids...)
}

// ClearConcepts clears all "concepts" edges to the Concept entity.
func (_u *TutorialContentUpdateOne) ClearConcepts() *TutorialContentUpdateOne {
	_u.mutation.ClearConcepts()
	return _u
}

// RemoveConceptIDs removes the "concepts" edge to Concept entities by IDs.
func (_u *TutorialContentUpdateOne) RemoveConceptIDs(ids ...uuid.UUID) *TutorialContentUpdateOne {
	_u.mutation.RemoveConceptIDs(ids...)
	return _u
}

// RemoveConcepts removes "concepts" edges to Concept entities.
func (_u *TutorialContentUpdateOne) RemoveConcepts(v ...*Concept) *TutorialContentUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConceptIDs(ids...)
}

// Where appends a list predicates to the TutorialContentUpdate builder.
func (_u *TutorialContentUpdateOne) Where(ps ...predicate.TutorialContent) *TutorialContentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TutorialContentUpdateOne) Select(field string, fields ...string) *TutorialContentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TutorialContent entity.
func (_u *TutorialContentUpdateOne) Save(ctx context.Context) (*TutorialContent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TutorialContentUpdateOne) SaveX(ctx context.Context) *TutorialContent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TutorialContentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TutorialContentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TutorialContentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tutorialcontent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TutorialContentUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := tutorialcontent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "TutorialContent.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tutorialcontent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TutorialContent.status": %w`, err)}
		}
	}
	if _u.mutation.IssueCleared() && len(_u.mutation.IssueIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TutorialContent.issue"`)
	}
	return nil
}

func (_u *TutorialContentUpdateOne) sqlSave(ctx context.Context) (_node *TutorialContent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tutorialcontent.Table, tutorialcontent.Columns, sqlgraph.NewFieldSpec(tutorialcontent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TutorialContent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tutorialcontent.FieldID)
		for _, f := range fields {
			if !tutorialcontent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tutorialcontent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(tutorialcontent.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.MarkdownBody(); ok {
		_spec.SetField(tutorialcontent.FieldMarkdownBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tutorialcontent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tutorialcontent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.IssueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tutorialcontent.IssueTable,
			Columns: []string{tutorialcontent.IssueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubissue.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IssueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tutorialcontent.IssueTable,
			Columns: []string{tutorialcontent.IssueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubissue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TutorialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tutorialcontent.TutorialsTable,
			Columns: []string{tutorialcontent.TutorialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorial.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTutorialsIDs(); len(nodes) > 0 && !_u.mutation.TutorialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tutorialcontent.TutorialsTable,
			Columns: []string{tutorialcontent.TutorialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorial.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TutorialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tutorialcontent.TutorialsTable,
			Columns: []string{tutorialcontent.TutorialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorial.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tutorialcontent.ConceptsTable,
			Columns: tutorialcontent.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConceptsIDs(); len(nodes) > 0 && !_u.mutation.ConceptsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tutorialcontent.ConceptsTable,
			Columns: tutorialcontent.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConceptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tutorialcontent.ConceptsTable,
			Columns: tutorialcontent.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TutorialContent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tutorialcontent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
