// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/concept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialconcept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialcontent"
)

// TutorialConceptCreate is the builder for creating a TutorialConcept entity.
type TutorialConceptCreate struct {
	config
	mutation *TutorialConceptMutation
	hooks    []Hook
}

// SetContentID sets the "content_id" field.
func (_c *TutorialConceptCreate) SetContentID(v uuid.UUID) *TutorialConceptCreate {
	_c.mutation.SetContentID(v)
	return _c
}

// SetConceptID sets the "concept_id" field.
func (_c *TutorialConceptCreate) SetConceptID(v uuid.UUID) *TutorialConceptCreate {
	_c.mutation.SetConceptID(v)
	return _c
}

// SetContent sets the "content" edge to the TutorialContent entity.
func (_c *TutorialConceptCreate) SetContent(v *TutorialContent) *TutorialConceptCreate {
	return _c.SetContentID(v.ID)
}

// SetConcept sets the "concept" edge to the Concept entity.
func (_c *TutorialConceptCreate) SetConcept(v *Concept) *TutorialConceptCreate {
	return _c.SetConceptID(v.ID)
}

// Mutation returns the TutorialConceptMutation object of the builder.
func (_c *TutorialConceptCreate) Mutation() *TutorialConceptMutation {
	return _c.mutation
}

// Save creates the TutorialConcept in the database.
func (_c *TutorialConceptCreate) Save(ctx context.Context) (*TutorialConcept, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TutorialConceptCreate) SaveX(ctx context.Context) *TutorialConcept {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TutorialConceptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TutorialConceptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TutorialConceptCreate) check() error {
	if _, ok := _c.mutation.ContentID(); !ok {
		return &ValidationError{Name: "content_id", err: errors.New(`ent: missing required field "TutorialConcept.content_id"`)}
	}
	if _, ok := _c.mutation.ConceptID(); !ok {
		return &ValidationError{Name: "concept_id", err: errors.New(`ent: missing required field "TutorialConcept.concept_id"`)}
	}
	if len(_c.mutation.ContentIDs()) == 0 {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required edge "TutorialConcept.content"`)}
	}
	if len(_c.mutation.ConceptIDs()) == 0 {
		return &ValidationError{Name: "concept", err: errors.New(`ent: missing required edge "TutorialConcept.concept"`)}
	}
	return nil
}

func (_c *TutorialConceptCreate) sqlSave(ctx context.Context) (*TutorialConcept, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *TutorialConceptCreate) createSpec() (*TutorialConcept, *sqlgraph.CreateSpec) {
	var (
		_node = &TutorialConcept{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tutorialconcept.Table, nil)
	)
	if nodes := _c.mutation.ContentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tutorialconcept.ContentTable,
			Columns: []string{tutorialconcept.ContentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorialcontent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ContentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ConceptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tutorialconcept.ConceptTable,
			Columns: []string{tutorialconcept.ConceptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConceptID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TutorialConceptCreateBulk is the builder for creating many TutorialConcept entities in bulk.
type TutorialConceptCreateBulk struct {
	config
	err      error
	builders []*TutorialConceptCreate
}

// Save creates the TutorialConcept entities in the database.
func (_c *TutorialConceptCreateBulk) Save(ctx context.Context) ([]*TutorialConcept, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TutorialConcept, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TutorialConceptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TutorialConceptCreateBulk) SaveX(ctx context.Context) []*TutorialConcept {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TutorialConceptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TutorialConceptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
