// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/concept"
	"github.com/issuesight/issuesight/internal/platform/db/ent/githubissue"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorial"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialcontent"
)

// TutorialContentCreate is the builder for creating a TutorialContent entity.
type TutorialContentCreate struct {
	config
	mutation *TutorialContentMutation
	hooks    []Hook
}

// SetIssueID sets the "issue_id" field.
func (_c *TutorialContentCreate) SetIssueID(v uuid.UUID) *TutorialContentCreate {
	_c.mutation.SetIssueID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *TutorialContentCreate) SetTitle(v string) *TutorialContentCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetMarkdownBody sets the "markdown_body" field.
func (_c *TutorialContentCreate) SetMarkdownBody(v string) *TutorialContentCreate {
	_c.mutation.SetMarkdownBody(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TutorialContentCreate) SetStatus(v tutorialcontent.Status) *TutorialContentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TutorialContentCreate) SetNillableStatus(v *tutorialcontent.Status) *TutorialContentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TutorialContentCreate) SetCreatedAt(v time.Time) *TutorialContentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TutorialContentCreate) SetNillableCreatedAt(v *time.Time) *TutorialContentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TutorialContentCreate) SetUpdatedAt(v time.Time) *TutorialContentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TutorialContentCreate) SetNillableUpdatedAt(v *time.Time) *TutorialContentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TutorialContentCreate) SetID(v uuid.UUID) *TutorialContentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TutorialContentCreate) SetNillableID(v *uuid.UUID) *TutorialContentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetIssue sets the "issue" edge to the GithubIssue entity.
func (_c *TutorialContentCreate) SetIssue(v *GithubIssue) *TutorialContentCreate {
	return _c.SetIssueID(v.ID)
}

// AddTutorialIDs adds the "tutorials" edge to the Tutorial entity by IDs.
func (_c *TutorialContentCreate) AddTutorialIDs(ids ...uuid.UUID) *TutorialContentCreate {
	_c.mutation.AddTutorialIDs(ids...)
	return _c
}

// AddTutorials adds the "tutorials" edges to the Tutorial entity.
func (_c *TutorialContentCreate) AddTutorials(v ...*Tutorial) *TutorialContentCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTutorialIDs(ids...)
}

// AddConceptIDs adds the "concepts" edge to the Concept entity by IDs.
func (_c *TutorialContentCreate) AddConceptIDs(ids ...uuid.UUID) *TutorialContentCreate {
	_c.mutation.AddConceptIDs(ids...)
	return _c
}

// AddConcepts adds the "concepts" edges to the Concept entity.
func (_c *TutorialContentCreate) AddConcepts(v ...*Concept) *TutorialContentCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddConceptIDs(ids...)
}

// Mutation returns the TutorialContentMutation object of the builder.
func (_c *TutorialContentCreate) Mutation() *TutorialContentMutation {
	return _c.mutation
}

// Save creates the TutorialContent in the database.
func (_c *TutorialContentCreate) Save(ctx context.Context) (*TutorialContent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TutorialContentCreate) SaveX(ctx context.Context) *TutorialContent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TutorialContentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TutorialContentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TutorialContentCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := tutorialcontent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tutorialcontent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := tutorialcontent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := tutorialcontent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TutorialContentCreate) check() error {
	if _, ok := _c.mutation.IssueID(); !ok {
		return &ValidationError{Name: "issue_id", err: errors.New(`ent: missing required field "TutorialContent.issue_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "TutorialContent.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := tutorialcontent.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "TutorialContent.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MarkdownBody(); !ok {
		return &ValidationError{Name: "markdown_body", err: errors.New(`ent: missing required field "TutorialContent.markdown_body"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TutorialContent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := tutorialcontent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TutorialContent.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TutorialContent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TutorialContent.updated_at"`)}
	}
	if len(_c.mutation.IssueIDs()) == 0 {
		return &ValidationError{Name: "issue", err: errors.New(`ent: missing required edge "TutorialContent.issue"`)}
	}
	return nil
}

func (_c *TutorialContentCreate) sqlSave(ctx context.Context) (*TutorialContent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TutorialContentCreate) createSpec() (*TutorialContent, *sqlgraph.CreateSpec) {
	var (
		_node = &TutorialContent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tutorialcontent.Table, sqlgraph.NewFieldSpec(tutorialcontent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(tutorialcontent.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.MarkdownBody(); ok {
		_spec.SetField(tutorialcontent.FieldMarkdownBody, field.TypeString, value)
		_node.MarkdownBody = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(tutorialcontent.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tutorialcontent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tutorialcontent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.IssueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tutorialcontent.IssueTable,
			Columns: []string{tutorialcontent.IssueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(githubissue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.IssueID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TutorialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tutorialcontent.TutorialsTable,
			Columns: []string{tutorialcontent.TutorialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorial.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ConceptsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tutorialcontent.ConceptsTable,
			Columns: tutorialcontent.ConceptsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(concept.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TutorialContentCreateBulk is the builder for creating many TutorialContent entities in bulk.
type TutorialContentCreateBulk struct {
	config
	err      error
	builders []*TutorialContentCreate
}

// Save creates the TutorialContent entities in the database.
func (_c *TutorialContentCreateBulk) Save(ctx context.Context) ([]*TutorialContent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TutorialContent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TutorialContentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TutorialContentCreateBulk) SaveX(ctx context.Context) []*TutorialContent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TutorialContentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TutorialContentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
