// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/predicate"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorial"
	"github.com/issuesight/issuesight/internal/platform/db/ent/tutorialcontent"
	"github.com/issuesight/issuesight/internal/platform/db/ent/user"
)

// TutorialUpdate is the builder for updating Tutorial entities.
type TutorialUpdate struct {
	config
	hooks    []Hook
	mutation *TutorialMutation
}

// Where appends a list predicates to the TutorialUpdate builder.
func (_u *TutorialUpdate) Where(ps ...predicate.Tutorial) *TutorialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TutorialUpdate) SetUserID(v uuid.UUID) *TutorialUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TutorialUpdate) SetNillableUserID(v *uuid.UUID) *TutorialUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetContentID sets the "content_id" field.
func (_u *TutorialUpdate) SetContentID(v uuid.UUID) *TutorialUpdate {
	_u.mutation.SetContentID(v)
	return _u
}

// SetNillableContentID sets the "content_id" field if the given value is not nil.
func (_u *TutorialUpdate) SetNillableContentID(v *uuid.UUID) *TutorialUpdate {
	if v != nil {
		_u.SetContentID(*v)
	}
	return _u
}

// SetIsOriginalRequester sets the "is_original_requester" field.
func (_u *TutorialUpdate) SetIsOriginalRequester(v bool) *TutorialUpdate {
	_u.mutation.SetIsOriginalRequester(v)
	return _u
}

// SetNillableIsOriginalRequester sets the "is_original_requester" field if the given value is not nil.
func (_u *TutorialUpdate) SetNillableIsOriginalRequester(v *bool) *TutorialUpdate {
	if v != nil {
		_u.SetIsOriginalRequester(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TutorialUpdate) SetUser(v *User) *TutorialUpdate {
	return _u.SetUserID(v.ID)
}

// SetContent sets the "content" edge to the TutorialContent entity.
func (_u *TutorialUpdate) SetContent(v *TutorialContent) *TutorialUpdate {
	return _u.SetContentID(v.ID)
}

// Mutation returns the TutorialMutation object of the builder.
func (_u *TutorialUpdate) Mutation() *TutorialMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TutorialUpdate) ClearUser() *TutorialUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearContent clears the "content" edge to the TutorialContent entity.
func (_u *TutorialUpdate) ClearContent() *TutorialUpdate {
	_u.mutation.ClearContent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TutorialUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TutorialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TutorialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TutorialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TutorialUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Tutorial.user"`)
	}
	if _u.mutation.ContentCleared() && len(_u.mutation.ContentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Tutorial.content"`)
	}
	return nil
}

func (_u *TutorialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tutorial.Table, tutorial.Columns, sqlgraph.NewFieldSpec(tutorial.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IsOriginalRequester(); ok {
		_spec.SetField(tutorial.FieldIsOriginalRequester, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tutorial.UserTable,
			Columns: []string{tutorial.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tutorial.UserTable,
			Columns: []string{tutorial.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tutorial.ContentTable,
			Columns: []string{tutorial.ContentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorialcontent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tutorial.ContentTable,
			Columns: []string{tutorial.ContentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorialcontent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tutorial.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TutorialUpdateOne is the builder for updating a single Tutorial entity.
type TutorialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TutorialMutation
}

// SetUserID sets the "user_id" field.
func (_u *TutorialUpdateOne) SetUserID(v uuid.UUID) *TutorialUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TutorialUpdateOne) SetNillableUserID(v *uuid.UUID) *TutorialUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetContentID sets the "content_id" field.
func (_u *TutorialUpdateOne) SetContentID(v uuid.UUID) *TutorialUpdateOne {
	_u.mutation.SetContentID(v)
	return _u
}

// SetNillableContentID sets the "content_id" field if the given value is not nil.
func (_u *TutorialUpdateOne) SetNillableContentID(v *uuid.UUID) *TutorialUpdateOne {
	if v != nil {
		_u.SetContentID(*v)
	}
	return _u
}

// SetIsOriginalRequester sets the "is_original_requester" field.
func (_u *TutorialUpdateOne) SetIsOriginalRequester(v bool) *TutorialUpdateOne {
	_u.mutation.SetIsOriginalRequester(v)
	return _u
}

// SetNillableIsOriginalRequester sets the "is_original_requester" field if the given value is not nil.
func (_u *TutorialUpdateOne) SetNillableIsOriginalRequester(v *bool) *TutorialUpdateOne {
	if v != nil {
		_u.SetIsOriginalRequester(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TutorialUpdateOne) SetUser(v *User) *TutorialUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetContent sets the "content" edge to the TutorialContent entity.
func (_u *TutorialUpdateOne) SetContent(v *TutorialContent) *TutorialUpdateOne {
	return _u.SetContentID(v.ID)
}

// Mutation returns the TutorialMutation object of the builder.
func (_u *TutorialUpdateOne) Mutation() *TutorialMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TutorialUpdateOne) ClearUser() *TutorialUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearContent clears the "content" edge to the TutorialContent entity.
func (_u *TutorialUpdateOne) ClearContent() *TutorialUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// Where appends a list predicates to the TutorialUpdate builder.
func (_u *TutorialUpdateOne) Where(ps ...predicate.Tutorial) *TutorialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TutorialUpdateOne) Select(field string, fields ...string) *TutorialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tutorial entity.
func (_u *TutorialUpdateOne) Save(ctx context.Context) (*Tutorial, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TutorialUpdateOne) SaveX(ctx context.Context) *Tutorial {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TutorialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TutorialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TutorialUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Tutorial.user"`)
	}
	if _u.mutation.ContentCleared() && len(_u.mutation.ContentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Tutorial.content"`)
	}
	return nil
}

func (_u *TutorialUpdateOne) sqlSave(ctx context.Context) (_node *Tutorial, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tutorial.Table, tutorial.Columns, sqlgraph.NewFieldSpec(tutorial.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tutorial.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tutorial.FieldID)
		for _, f := range fields {
			if !tutorial.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tutorial.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IsOriginalRequester(); ok {
		_spec.SetField(tutorial.FieldIsOriginalRequester, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tutorial.UserTable,
			Columns: []string{tutorial.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tutorial.UserTable,
			Columns: []string{tutorial.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tutorial.ContentTable,
			Columns: []string{tutorial.ContentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorialcontent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tutorial.ContentTable,
			Columns: []string{tutorial.ContentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tutorialcontent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Tutorial{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tutorial.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
