// Code generated by ent, DO NOT EDIT.

package tutorialcontent

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the tutorialcontent type in the database.
	Label = "tutorial_content"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIssueID holds the string denoting the issue_id field in the database.
	FieldIssueID = "issue_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldMarkdownBody holds the string denoting the markdown_body field in the database.
	FieldMarkdownBody = "markdown_body"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeIssue holds the string denoting the issue edge name in mutations.
	EdgeIssue = "issue"
	// EdgeTutorials holds the string denoting the tutorials edge name in mutations.
	EdgeTutorials = "tutorials"
	// EdgeConcepts holds the string denoting the concepts edge name in mutations.
	EdgeConcepts = "concepts"
	// EdgeTutorialConcepts holds the string denoting the tutorial_concepts edge name in mutations.
	EdgeTutorialConcepts = "tutorial_concepts"
	// Table holds the table name of the tutorialcontent in the database.
	Table = "tutorial_contents"
	// IssueTable is the table that holds the issue relation/edge.
	IssueTable = "tutorial_contents"
	// IssueInverseTable is the table name for the GithubIssue entity.
	// It exists in this package in order to avoid circular dependency with the "githubissue" package.
	IssueInverseTable = "github_issues"
	// IssueColumn is the table column denoting the issue relation/edge.
	IssueColumn = "issue_id"
	// TutorialsTable is the table that holds the tutorials relation/edge.
	TutorialsTable = "tutorials"
	// TutorialsInverseTable is the table name for the Tutorial entity.
	// It exists in this package in order to avoid circular dependency with the "tutorial" package.
	TutorialsInverseTable = "tutorials"
	// TutorialsColumn is the table column denoting the tutorials relation/edge.
	TutorialsColumn = "content_id"
	// ConceptsTable is the table that holds the concepts relation/edge. The primary key declared below.
	ConceptsTable = "tutorial_concepts"
	// ConceptsInverseTable is the table name for the Concept entity.
	// It exists in this package in order to avoid circular dependency with the "concept" package.
	ConceptsInverseTable = "concepts"
	// TutorialConceptsTable is the table that holds the tutorial_concepts relation/edge.
	TutorialConceptsTable = "tutorial_concepts"
	// TutorialConceptsInverseTable is the table name for the TutorialConcept entity.
	// It exists in this package in order to avoid circular dependency with the "tutorialconcept" package.
	TutorialConceptsInverseTable = "tutorial_concepts"
	// TutorialConceptsColumn is the table column denoting the tutorial_concepts relation/edge.
	TutorialConceptsColumn = "content_id"
)

// Columns holds all SQL columns for tutorialcontent fields.
var Columns = []string{
	FieldID,
	FieldIssueID,
	FieldTitle,
	FieldMarkdownBody,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// ConceptsPrimaryKey and ConceptsColumn2 are the table columns denoting the
	// primary key for the concepts relation (M2M).
	ConceptsPrimaryKey = []string{"content_id", "concept_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending   Status = "pending"
	StatusCompleted Status = "completed"
	StatusFailed    Status = "failed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusCompleted, StatusFailed:
		return nil
	default:
		return fmt.Errorf("tutorialcontent: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the TutorialContent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIssueID orders the results by the issue_id field.
func ByIssueID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssueID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByMarkdownBody orders the results by the markdown_body field.
func ByMarkdownBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMarkdownBody, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByIssueField orders the results by issue field.
func ByIssueField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIssueStep(), sql.OrderByField(field, opts...))
	}
}

// ByTutorialsCount orders the results by tutorials count.
func ByTutorialsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTutorialsStep(), opts...)
	}
}

// ByTutorials orders the results by tutorials terms.
func ByTutorials(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTutorialsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByConceptsCount orders the results by concepts count.
func ByConceptsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newConceptsStep(), opts...)
	}
}

// ByConcepts orders the results by concepts terms.
func ByConcepts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConceptsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTutorialConceptsCount orders the results by tutorial_concepts count.
func ByTutorialConceptsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTutorialConceptsStep(), opts...)
	}
}

// ByTutorialConcepts orders the results by tutorial_concepts terms.
func ByTutorialConcepts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTutorialConceptsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newIssueStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IssueInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, IssueTable, IssueColumn),
	)
}
func newTutorialsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TutorialsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TutorialsTable, TutorialsColumn),
	)
}
func newConceptsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConceptsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ConceptsTable, ConceptsPrimaryKey...),
	)
}
func newTutorialConceptsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TutorialConceptsInverseTable, TutorialConceptsColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, TutorialConceptsTable, TutorialConceptsColumn),
	)
}
