// Code generated by ent, DO NOT EDIT.

package tutorial

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/issuesight/issuesight/internal/platform/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldEQ(FieldUserID, v))
}

// ContentID applies equality check predicate on the "content_id" field. It's identical to ContentIDEQ.
func ContentID(v uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldEQ(FieldContentID, v))
}

// IsOriginalRequester applies equality check predicate on the "is_original_requester" field. It's identical to IsOriginalRequesterEQ.
func IsOriginalRequester(v bool) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldEQ(FieldIsOriginalRequester, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldNotIn(FieldUserID, vs...))
}

// ContentIDEQ applies the EQ predicate on the "content_id" field.
func ContentIDEQ(v uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldEQ(FieldContentID, v))
}

// ContentIDNEQ applies the NEQ predicate on the "content_id" field.
func ContentIDNEQ(v uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldNEQ(FieldContentID, v))
}

// ContentIDIn applies the In predicate on the "content_id" field.
func ContentIDIn(vs ...uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldIn(FieldContentID, vs...))
}

// ContentIDNotIn applies the NotIn predicate on the "content_id" field.
func ContentIDNotIn(vs ...uuid.UUID) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldNotIn(FieldContentID, vs...))
}

// IsOriginalRequesterEQ applies the EQ predicate on the "is_original_requester" field.
func IsOriginalRequesterEQ(v bool) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldEQ(FieldIsOriginalRequester, v))
}

// IsOriginalRequesterNEQ applies the NEQ predicate on the "is_original_requester" field.
func IsOriginalRequesterNEQ(v bool) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldNEQ(FieldIsOriginalRequester, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Tutorial {
	return predicate.Tutorial(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Tutorial {
	return predicate.Tutorial(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Tutorial {
	return predicate.Tutorial(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasContent applies the HasEdge predicate on the "content" edge.
func HasContent() predicate.Tutorial {
	return predicate.Tutorial(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ContentTable, ContentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContentWith applies the HasEdge predicate on the "content" edge with a given conditions (other predicates).
func HasContentWith(preds ...predicate.TutorialContent) predicate.Tutorial {
	return predicate.Tutorial(func(s *sql.Selector) {
		step := newContentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Tutorial) predicate.Tutorial {
	return predicate.Tutorial(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Tutorial) predicate.Tutorial {
	return predicate.Tutorial(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Tutorial) predicate.Tutorial {
	return predicate.Tutorial(sql.NotPredicates(p))
}
